@extends('layouts.dashboard')
@section('page-title', 'Customers')
@section('page-subtitle', 'Customer and dealer CRUD')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="tf-card p-4 mb-4"><h2 class="h5">Add Customer</h2><form method="POST" action="{{ route('business.customers.store') }}" class="row g-3">@csrf<div class="col-md-3"><input name="name" class="form-control" placeholder="Owner name"></div><div class="col-md-3"><input name="shop_name" class="form-control" placeholder="Shop name"></div><div class="col-md-2"><input name="phone" class="form-control" placeholder="Phone"></div><div class="col-md-2"><input name="city" class="form-control" placeholder="City"></div><div class="col-md-2"><select name="customer_type" class="form-select"><option>Retailer</option><option>Dealer</option><option>Wholesaler</option></select></div><div class="col-md-3"><input name="credit_limit" type="number" class="form-control" placeholder="Credit limit"></div><div class="col-md-7"><input name="address" class="form-control" placeholder="Address"></div><div class="col-md-2"><select name="status" class="form-select"><option>Active</option><option>Blocked</option></select></div><div class="col-12"><button class="btn btn-tf-primary">Save Customer</button></div></form></div>
<x-table><thead><tr><th>Name</th><th>Type</th><th>City</th><th>Credit Balance</th><th>Status</th><th></th></tr></thead><tbody>@forelse($customers ?? [] as $customer)<tr><td>{{ $customer->business_name ?: $customer->name }}</td><td>{{ $customer->customer_type }}</td><td>{{ $customer->city }}</td><td>Rs {{ number_format($customer->current_balance) }}</td><td>{{ $customer->status }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('business.customers.show', $customer) }}">Profile</a></td></tr>@empty<tr><td colspan="6" class="text-center tf-muted py-4">No customers yet.</td></tr>@endforelse</tbody></x-table>
@if(isset($customers) && method_exists($customers, 'links'))<div class="mt-3">{{ $customers->links() }}</div>@endif
@endsection
