@extends('layouts.dashboard')
@section('page-title', 'Customer Profile')
@section('page-subtitle', $customer->business_name ?: $customer->name)
@section('content')
<div class="row g-4">
    <div class="col-lg-4"><div class="tf-card p-4"><h2 class="h4">{{ $customer->business_name ?: $customer->name }}</h2><p class="tf-muted">{{ $customer->customer_type }}, {{ $customer->city }}</p><div class="h3 text-danger">Rs {{ number_format($customer->current_balance) }}</div><small class="tf-muted">Credit balance</small><div class="row g-2 mt-3"><div class="col-6"><div class="border rounded p-2"><small class="tf-muted">Orders</small><strong class="d-block">{{ $customer->orders->count() }}</strong></div></div><div class="col-6"><div class="border rounded p-2"><small class="tf-muted">Purchase</small><strong class="d-block">Rs {{ number_format($customer->orders->sum(fn($o) => $o->grand_total ?: $o->total)) }}</strong></div></div><div class="col-6"><div class="border rounded p-2"><small class="tf-muted">Last Payment</small><strong class="d-block">Rs {{ number_format($customer->payments->sortByDesc('payment_date')->first()?->amount ?? 0) }}</strong></div></div><div class="col-6"><div class="border rounded p-2"><small class="tf-muted">Pending</small><strong class="d-block">Rs {{ number_format($customer->current_balance) }}</strong></div></div></div><form method="POST" action="{{ route('business.customers.update', $customer) }}" class="mt-3">@csrf @method('PATCH')<select name="status" class="form-select mb-2"><option @selected($customer->status === 'Active')>Active</option><option @selected($customer->status === 'Blocked')>Blocked</option></select><button class="btn btn-outline-primary btn-sm">Update Status</button></form></div></div>
    <div class="col-lg-8"><x-table><thead><tr><th>Date</th><th>Order</th><th>Type</th><th>Amount</th><th>Balance</th></tr></thead><tbody>@forelse($customer->ledgers as $ledger)<tr><td>{{ $ledger->created_at->format('M d') }}</td><td>{{ $ledger->order?->order_number ?? '-' }}</td><td>{{ $ledger->type }}</td><td>Rs {{ number_format($ledger->amount) }}</td><td>Rs {{ number_format($ledger->balance) }}</td></tr>@empty<tr><td colspan="5" class="text-center tf-muted py-4">No ledger entries.</td></tr>@endforelse</tbody></x-table></div>
</div>
@endsection
