@php($money = static fn ($value) => 'Rs '.number_format((float) $value, 2))
<x-a4-document :business="$business" :footer="$business?->documentFooter" title="End of Day Report" :reference="$selectedDate->format('n/j/Y')" :date="$generatedAt->format('n/j/Y, g:i A')" :status="$report['status']" subtitle="Daily sales, payments, cash reconciliation, purchasing, expenses, and profitability.">
    <h2 style="font-size:12px; margin:0 0 6px;">Executive Summary</h2><table class="tf-a4-document__summary"><tr><td><span class="tf-a4-document__summary-label">Net sales</span><strong class="tf-a4-document__summary-value">{{ $money($report['sales']['net_sales']) }}</strong></td><td><span class="tf-a4-document__summary-label">Payments collected</span><strong class="tf-a4-document__summary-value">{{ $money($report['sales']['paid_sales'] + $report['payments']['customer_collections']) }}</strong></td><td><span class="tf-a4-document__summary-label">Gross profit</span><strong class="tf-a4-document__summary-value">{{ $money($report['profitability']['gross_profit']) }}</strong></td><td><span class="tf-a4-document__summary-label">Net profit</span><strong class="tf-a4-document__summary-value">{{ $money($report['profitability']['net_profit']) }}</strong></td></tr></table>
    <h2 style="font-size:12px; margin:14px 0 6px;">Sales and Payments</h2><table class="tf-a4-document__table"><tbody><tr><td>Invoices</td><td class="tf-a4-document__money">{{ number_format($report['sales']['invoice_count']) }}</td><td>Gross sales</td><td class="tf-a4-document__money">{{ $money($report['sales']['gross_sales']) }}</td></tr><tr><td>Line discounts (included)</td><td class="tf-a4-document__money">{{ $money($report['sales']['line_discounts_included']) }}</td><td>Invoice discounts</td><td class="tf-a4-document__money">-{{ $money($report['sales']['invoice_discounts']) }}</td></tr><tr><td>Sales returns</td><td class="tf-a4-document__money">-{{ $money($report['sales']['sales_returns']) }}</td><td>Total discounts (explanatory)</td><td class="tf-a4-document__money">{{ $money($report['sales']['total_discounts']) }}</td></tr><tr><td><strong>Net sales</strong></td><td class="tf-a4-document__money"><strong>{{ $money($report['sales']['net_sales']) }}</strong></td><td>Credit generated</td><td class="tf-a4-document__money">{{ $money($report['sales']['credit_sales']) }}</td></tr>@foreach($report['payments']['breakdown'] as $method => $amount)<tr><td>Payment · {{ $method }}</td><td class="tf-a4-document__money">{{ $money($amount) }}</td><td></td><td></td></tr>@endforeach<tr><td>Customer collections</td><td class="tf-a4-document__money">{{ $money($report['payments']['customer_collections']) }}</td><td></td><td></td></tr></tbody></table>
    @if($canPos && $report['registers'])
        <h2 style="font-size:12px; margin:14px 0 6px;">Cash Register Reconciliation</h2>
        <table class="tf-a4-document__table"><thead><tr><th>Cashier</th><th>Open</th><th>Close</th><th class="tf-a4-document__money">Expected</th><th class="tf-a4-document__money">Actual</th><th class="tf-a4-document__money">Variance</th></tr></thead><tbody>
            @forelse($report['registers']['rows'] as $shift)
                <tr><td>{{ $shift['cashier'] }}</td><td>{{ $shift['opened_at']?->format('g:i A') ?? '—' }}</td><td>{{ $shift['closed_at']?->format('g:i A') ?? 'Pending' }}</td><td class="tf-a4-document__money">{{ $money($shift['expected_cash']) }}</td><td class="tf-a4-document__money">{{ $shift['actual_cash'] === null ? 'Pending' : $money($shift['actual_cash']) }}</td><td class="tf-a4-document__money">{{ $shift['variance'] === null ? '—' : $money($shift['variance']) }}</td></tr>
            @empty
                <tr><td class="tf-a4-document__empty" colspan="6">No POS register shifts opened on this date.</td></tr>
            @endforelse
        </tbody></table>
        @if($report['registers']['open_count'])
            <p class="tf-a4-document__warning">Daily cash reconciliation is incomplete because {{ $report['registers']['open_count'] }} POS register remains open.</p>
        @endif
    @endif
    @if($canPurchases && $report['purchases'])<h2 style="font-size:12px; margin:14px 0 6px;">Purchases and Expenses</h2><table class="tf-a4-document__table"><tbody><tr><td>Purchases</td><td class="tf-a4-document__money">{{ $money($report['purchases']['amount']) }}</td><td>Supplier payments</td><td class="tf-a4-document__money">{{ $money($report['purchases']['supplier_payments']) }}</td></tr><tr><td>Purchase returns</td><td class="tf-a4-document__money">{{ $money($report['purchases']['purchase_returns']) }}</td><td>GRNs received</td><td class="tf-a4-document__money">{{ number_format($report['purchases']['grn_count']) }}</td></tr><tr><td>Operating expenses</td><td class="tf-a4-document__money">{{ $money($report['expenses']['total']) }}</td><td></td><td></td></tr></tbody></table>@endif
    <h2 style="font-size:12px; margin:14px 0 6px;">Profitability</h2><table class="tf-a4-document__table"><tbody><tr><td>Net sales</td><td class="tf-a4-document__money">{{ $money($report['profitability']['net_sales']) }}</td></tr><tr><td>COGS</td><td class="tf-a4-document__money">-{{ $money($report['profitability']['cogs']) }}</td></tr><tr><td><strong>Gross profit</strong></td><td class="tf-a4-document__money"><strong>{{ $money($report['profitability']['gross_profit']) }}</strong></td></tr><tr><td>Expenses</td><td class="tf-a4-document__money">-{{ $money($report['profitability']['expenses']) }}</td></tr><tr><td><strong>{{ $report['profitability']['net_profit'] < 0 ? 'Net loss' : 'Net profit' }}</strong></td><td class="tf-a4-document__money"><strong>{{ $money($report['profitability']['net_profit']) }}</strong></td></tr></tbody></table>
</x-a4-document>
