@extends('layouts.dashboard')
@section('page-title', 'Reports')
@section('page-subtitle', 'Sales, inventory, finance, and customer reports')
@section('content')
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@if(($filtersApplied ?? false) && (($filteredOrdersCount ?? 0) + ($filteredExpensesCount ?? 0) === 0))<div class="alert alert-warning">No report data found for the selected filters. Adjust the date range or status and try again.</div>@endif
<form class="tf-card p-4 mb-4 row g-3">
    <div class="col-md-3"><label class="form-label">Date From</label><input name="date_from" type="date" value="{{ request('date_from', now()->format('Y-m-d')) }}" class="form-control"></div>
    <div class="col-md-3"><label class="form-label">Date To</label><input name="date_to" type="date" value="{{ request('date_to', now()->format('Y-m-d')) }}" class="form-control"></div>
    <div class="col-md-2"><label class="form-label">Month</label><select name="month" class="form-select"><option value="">All</option>@for($m = 1; $m <= 12; $m++)<option value="{{ $m }}" @selected((string) request('month') === (string) $m)>{{ \Illuminate\Support\Carbon::create()->month($m)->format('M') }}</option>@endfor</select></div>
    <div class="col-md-2"><label class="form-label">Year</label><input name="year" type="number" class="form-control" value="{{ request('year') }}" placeholder="{{ now()->year }}"></div>
    <div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All Statuses</option>@foreach(['New','Accepted','Packing','Ready','Delivered','Completed','Cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Customer</label><select name="customer_id" class="form-select"><option value="">All Customers</option>@foreach($customers ?? [] as $customer)<option value="{{ $customer->id }}" @selected((string) request('customer_id') === (string) $customer->id)>{{ $customer->business_name ?: $customer->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Product</label><select name="product_id" class="form-select"><option value="">All Products</option>@foreach($products ?? [] as $product)<option value="{{ $product->id }}" @selected((string) request('product_id') === (string) $product->id)>{{ $product->name }}</option>@endforeach</select></div>
    <div class="col-md-2 d-flex align-items-end"><button class="btn btn-outline-primary w-100">Apply Filters</button></div>
    <div class="col-md-2 d-flex align-items-end"><a href="{{ route('business.reports') }}" class="btn btn-outline-secondary w-100">Clear</a></div>
</form>
<div class="row g-4 mb-4">@foreach([['Subtotal','Rs '.number_format($subtotal ?? 0),'bi-calculator'],['Discount Amount','Rs '.number_format($discountAmount ?? 0),'bi-percent'],['Sales Total','Rs '.number_format($sales ?? 0),'bi-bar-chart'],['Revenue Received','Rs '.number_format($revenue ?? 0),'bi-cash-coin'],['Balance','Rs '.number_format($balance ?? 0),'bi-wallet2'],['Today Sales','Rs '.number_format($todaySales ?? 0),'bi-calendar-day'],['Monthly Sales','Rs '.number_format($monthlySales ?? 0),'bi-calendar-month'],['Completed Orders',$completedOrders ?? 0,'bi-check-circle'],['Pending Orders',$pendingOrders ?? 0,'bi-hourglass'],['Stock Value','Rs '.number_format($stockValue ?? 0),'bi-boxes'],['Expenses','Rs '.number_format($expenses ?? 0),'bi-receipt'],['Profit/Loss','Rs '.number_format($profit ?? 0),'bi-graph-up']] as [$title,$value,$icon])<div class="col-md-6 col-xl-4"><div class="tf-card p-4"><div class="tf-icon-tile bg-blue text-white mb-3"><i class="bi {{ $icon }}"></i></div><h2 class="h6">{{ $title }}</h2><p class="h3 fw-bold mb-0">{{ $value }}</p></div></div>@endforeach</div>
<div class="tf-card p-4 mb-4"><h2 class="h5">Export PDF</h2><div class="d-flex flex-wrap gap-2">@foreach(['sales'=>'Sales Report','inventory'=>'Inventory Report','expense'=>'Expense Report','profit-loss'=>'Profit/Loss Report'] as $type=>$label)<a href="{{ route('business.reports.pdf', array_merge(['type' => $type], request()->query())) }}" target="_blank" rel="noopener" class="btn btn-outline-primary"><i class="bi bi-filetype-pdf me-1"></i>{{ $label }}</a>@endforeach</div></div>
<div class="row g-4"><div class="col-lg-6"><div class="tf-card p-4"><h2 class="h5">Low Stock Products</h2>@forelse($lowStockProducts ?? [] as $product)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $product->name }}</span><strong>{{ $product->stock_quantity }}</strong></div>@empty<p class="tf-muted">No low stock products.</p>@endforelse</div></div><div class="col-lg-6"><div class="tf-card p-4"><h2 class="h5">Top Credit Customers</h2>@forelse($topCustomers ?? [] as $customer)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $customer->business_name ?: $customer->name }}</span><strong>Rs {{ number_format($customer->current_balance) }}</strong></div>@empty<p class="tf-muted">No customers yet.</p>@endforelse</div></div></div>
@endsection
