@extends('layouts.dashboard')
@section('page-title', $row->name.' Performance')
@section('page-subtitle', 'Read-only product revenue, margin, and return details')
@section('content')
@php($money = static fn ($value) => 'Rs '.number_format((float) $value, 2))
@php($quantity = static fn ($value) => rtrim(rtrim(number_format((float) $value, 3, '.', ''), '0'), '.') ?: '0')
<div class="d-flex justify-content-between align-items-center mb-3"><a class="btn btn-sm btn-outline-primary" href="{{ route('business.reports.product-performance', request()->query()) }}"><i class="bi bi-arrow-left me-1"></i>Product Performance</a>@if($canEditProducts)<a class="btn btn-sm btn-outline-primary" href="{{ route('business.products.bulk-pricing') }}">Open Bulk Pricing</a>@endif</div>
<div class="row g-3"><div class="col-lg-5"><section class="tf-card p-4 h-100"><span class="tf-dashboard-eyebrow">Product</span><h2 class="h5">{{ $row->name }}</h2><dl class="row small mb-0"><dt class="col-5">Category</dt><dd class="col-7">{{ $row->category }}</dd><dt class="col-5">Unit</dt><dd class="col-7">{{ $row->unit }}</dd><dt class="col-5">Retail price</dt><dd class="col-7">{{ $money($row->retail_price) }}</dd><dt class="col-5">Wholesale price</dt><dd class="col-7">{{ $money($row->wholesale_price) }}</dd></dl></section></div><div class="col-lg-7"><section class="tf-card p-4 h-100"><span class="tf-dashboard-eyebrow">Performance</span><div class="row g-3 mt-1"><div class="col-sm-4"><small class="tf-muted d-block">Qty Sold</small><strong>{{ $quantity($row->qty_sold) }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">Qty Returned</small><strong>{{ $quantity($row->qty_returned) }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">Net Qty</small><strong>{{ $quantity($row->net_qty_sold) }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">Net Sales</small><strong>{{ $money($row->net_sales) }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">COGS</small><strong>{{ $money($row->cogs) }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">Gross Profit</small><strong class="{{ $row->gross_profit < 0 ? 'text-danger' : 'text-success' }}">{{ $money($row->gross_profit) }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">Gross Margin</small><strong>{{ $row->gross_margin === null ? '—' : number_format($row->gross_margin, 2).'%' }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">Return Value</small><strong>{{ $money($row->return_value) }}</strong></div><div class="col-sm-4"><small class="tf-muted d-block">Return Rate</small><strong>{{ $row->return_rate === null ? '—' : number_format($row->return_rate, 2).'%' }}</strong></div></div></section></div></div>
@if($canViewReturns)<section class="tf-card p-4 mt-3"><span class="tf-dashboard-eyebrow">Returns</span><h2 class="h6">Recorded return reasons</h2>@if($row->return_reasons->isEmpty())<p class="tf-muted mb-0">No recorded returns for this product in the selected period.</p>@else<div class="d-flex flex-wrap gap-2">@foreach($row->return_reasons as $reason)<span class="badge text-bg-light border text-dark">{{ $reason->reason }} · {{ $quantity($reason->quantity) }}</span>@endforeach</div>@endif</section>@endif
@endsection
