@extends('layouts.dashboard')
@section('page-title', 'Stock Movement Analytics')
@section('page-subtitle', 'Fast, slow, and dead stock based on completed sales and current sellable inventory')
@section('content')
@php($quantity = static fn ($value) => rtrim(rtrim(number_format((float) $value, 3, '.', ''), '0'), '.') ?: '0')
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-1">Inventory analytics</h2><p class="tf-muted mb-0">Movement status is based on net completed sales during the selected period and the configured dead-stock threshold.</p></div><div class="d-flex gap-2"><a href="{{ route('business.reports') }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-arrow-left me-1"></i>Reports</a>@if($canExport)<a target="_blank" class="btn btn-sm btn-outline-primary" href="{{ route('business.reports.stock-movement-analytics.pdf', request()->query()) }}"><i class="bi bi-filetype-pdf me-1"></i>Export PDF</a>@endif</div></div>

<div class="row g-3 mb-3"><div class="col-sm-6 col-xl-3"><div class="tf-card p-3 h-100"><small class="tf-muted d-block">Fast Moving Products</small><strong class="fs-4 text-success">{{ number_format($summary['fast']) }}</strong></div></div><div class="col-sm-6 col-xl-3"><div class="tf-card p-3 h-100"><small class="tf-muted d-block">Slow Moving Products</small><strong class="fs-4 text-warning">{{ number_format($summary['slow']) }}</strong></div></div><div class="col-sm-6 col-xl-3"><div class="tf-card p-3 h-100"><small class="tf-muted d-block">Dead Stock Products</small><strong class="fs-4 text-danger">{{ number_format($summary['dead']) }}</strong></div></div><div class="col-sm-6 col-xl-3"><div class="tf-card p-3 h-100"><small class="tf-muted d-block">Dead Stock Value</small><strong class="fs-4 text-danger">Rs {{ number_format($summary['dead_value'], 2) }}</strong></div></div></div>

<form method="GET" class="tf-card p-3 mb-3"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">Search product</label><input class="form-control" name="search" value="{{ $filters['search'] }}" placeholder="Name or barcode"></div><div class="col-md-2"><label class="form-label">Category</label><select name="category_id" class="form-select"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($filters['category_id'] == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Unit</label><select name="unit_id" class="form-select"><option value="">All units</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($filters['unit_id'] == $unit->id)>{{ $unit->short_code ?: $unit->unit_name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Movement status</label><select name="status" class="form-select"><option value="all">All statuses</option>@foreach(['fast-moving'=>'Fast Moving','slow-moving'=>'Slow Moving','dead-stock'=>'Dead Stock','normal'=>'Normal','no-sales-history'=>'No Sales History'] as $key => $label)<option value="{{ $key }}" @selected($filters['status'] === $key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-1"><label class="form-label">Period</label><select name="period" class="form-select">@foreach([30,60,90] as $days)<option value="{{ $days }}" @selected($filters['period'] === $days)>{{ $days }}d</option>@endforeach</select></div><div class="col-md-1"><label class="form-label">Dead after</label><select name="dead_threshold" class="form-select">@foreach([30,60,90,180] as $days)<option value="{{ $days }}" @selected($filters['dead_threshold'] === $days)>{{ $days }}d</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Sort</label><select name="sort" class="form-select">@foreach(['qty_sold'=>'Qty Sold','stock'=>'Current Stock','inventory_value'=>'Inventory Value','last_sale'=>'Last Sale','days_since_sale'=>'Days Since Sale'] as $key => $label)<option value="{{ $key }}" @selected($filters['sort'] === $key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Rows</label><select name="per_page" class="form-select">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected($filters['per_page'] === $size)>{{ $size }}</option>@endforeach</select></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-tf-primary flex-grow-1">Filter</button><a class="btn btn-outline-primary" href="{{ route('business.reports.stock-movement-analytics') }}">Clear</a></div></div></form>

<div class="alert alert-light border small mb-3"><i class="bi bi-info-circle me-1"></i><strong>Classification:</strong> Fast Moving is the top 20% of products with net sales quantity in this period (at least one product). Slow Moving is the bottom 25% of products with positive sales and sellable stock. Dead Stock has sellable stock and no valid sale for the threshold, or no sales with a reliable stock age beyond it. Returns processed in the period reduce net movement.</div>
<div class="tf-card overflow-hidden"><div class="table-responsive"><table class="table align-middle mb-0 tf-business-data-table"><thead><tr><th>Product</th><th>Category</th><th>Unit</th><th class="text-end">Current Stock</th><th class="text-end">Qty Sold</th><th class="text-end">Avg / Day</th><th>Last Sale</th><th class="text-end">Days Since</th><th class="text-end">Inventory Value</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($analytics as $row)@php($badge = match($row->movement_status) {'Fast Moving'=>'text-bg-success','Slow Moving'=>'text-bg-warning','Dead Stock'=>'text-bg-danger','Normal'=>'text-bg-primary',default=>'text-bg-secondary'})<tr><td><strong>{{ $row->name }}</strong>@if($row->expired_stock > 0)<small class="d-block text-warning">{{ $quantity($row->expired_stock) }} expired excluded</small>@endif</td><td>{{ $row->category }}</td><td>{{ $row->unit }}</td><td class="text-end">{{ $quantity($row->current_stock) }}</td><td class="text-end">{{ $quantity($row->qty_sold) }}@if($row->returned_quantity > 0)<small class="d-block tf-muted">{{ $quantity($row->returned_quantity) }} returned</small>@endif</td><td class="text-end">{{ $quantity($row->average_daily_qty) }}</td><td>{{ $row->last_sale_at?->format('n/j/Y') ?? '—' }}</td><td class="text-end">{{ $row->days_since_sale ?? '—' }}</td><td class="text-end">Rs {{ number_format($row->inventory_value, 2) }}</td><td><span class="badge {{ $badge }}">{{ $row->movement_status }}</span>@if($row->movement_status === 'Fast Moving' && $row->suggested_quantity > 0)<small class="d-block text-primary">Reorder: {{ $quantity($row->suggested_quantity) }}</small>@endif</td><td>@if($canViewProducts)<a href="{{ route('business.products.show', $row->product) }}" class="btn btn-sm btn-outline-primary">View Product</a>@else<span class="tf-muted">—</span>@endif</td></tr>@empty<tr><td colspan="11" class="text-center tf-muted py-5">No product analytics match the selected filters.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3"><x-table-result-summary :paginator="$analytics" />{{ $analytics->links('pagination::bootstrap-5') }}</div>
@endsection
