@extends('layouts.dashboard')

@section('page-title', 'Supplier Aging')
@section('page-subtitle', 'Outstanding supplier payables by due date')

@section('content')
@php
    $money = static fn ($amount) => 'Rs '.number_format((float) $amount, 2);
    $labels = ['current' => 'Current', 'days_1_30' => '1–30 Days', 'days_31_60' => '31–60 Days', 'days_61_90' => '61–90 Days', 'days_90_plus' => '90+ Days'];
    $tones = ['current' => 'primary', 'days_1_30' => 'warning', 'days_31_60' => 'warning', 'days_61_90' => 'orange', 'days_90_plus' => 'danger'];
@endphp
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><h2 class="h5 mb-1">Payables Aging</h2><p class="tf-muted mb-0">Outstanding purchases are grouped by due date, or purchase date when no due date exists.</p></div>@companyCan('reports.export')<a class="btn btn-outline-primary" href="{{ route('business.reports.supplier-aging.pdf', request()->query()) }}" target="_blank" rel="noopener"><i class="bi bi-filetype-pdf me-1"></i>Export PDF</a>@endcompanyCan</div>

<section class="tf-card p-3 mb-3"><form class="row g-2 align-items-end" method="GET"><div class="col-md-3"><label class="form-label">Supplier</label><select name="party_id" class="form-select" data-native-select><option value="">All suppliers</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((string) $filters['party_id'] === (string) $supplier->id)>{{ $supplier->company_name ?: $supplier->supplier_name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Aging Bucket</label><select name="bucket" class="form-select"><option value="">All buckets</option>@foreach($labels as $key => $label)<option value="{{ $key }}" @selected($filters['bucket'] === $key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">As of Date</label><input name="as_of" type="date" max="{{ now(config('app.timezone'))->toDateString() }}" value="{{ $filters['as_of'] }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Minimum Outstanding</label><input name="minimum_outstanding" type="number" min="0" step="0.01" value="{{ $filters['minimum_outstanding'] }}" class="form-control" placeholder="Rs 0"></div><div class="col-md-2"><label class="form-label">Search</label><input name="search" value="{{ $filters['search'] }}" class="form-control" placeholder="Supplier name"></div><div class="col-md-1 d-flex gap-2"><button class="btn btn-tf-primary" type="submit">Filter</button><a class="btn btn-outline-primary" href="{{ route('business.reports.supplier-aging') }}">Clear</a></div></form><small class="tf-muted d-block mt-2">Current aging is authoritative. Historic snapshots are unavailable where legacy payments have no purchase allocation.</small></section>

<section class="row g-3 mb-2"><div class="col-12 col-md-4 col-lg-3"><article class="tf-card p-3 h-100"><span class="tf-muted small">Total Payables</span><strong class="d-block fs-4 mt-1">{{ $money($summary['total_outstanding']) }}</strong></article></div>@foreach($labels as $key => $label)<div class="col-6 col-md-4 col-lg"><article class="tf-card p-3 h-100"><span class="tf-muted small">{{ $label }}</span><strong class="d-block fs-5 mt-1 text-{{ $tones[$key] }}">{{ $money($summary[$key]) }}</strong></article></div>@endforeach</section><p class="tf-muted small mb-4">Includes {{ $money($summary['unallocated_current'] ?? 0) }} in opening balances and unallocated balance adjustments in Current. These amounts are not assigned to a purchase.</p>

<section class="tf-card p-0 overflow-hidden"><div class="p-3 border-bottom"><h2 class="h5 mb-1">Supplier Payables</h2><p class="tf-muted small mb-0">Only purchases with an outstanding amount are shown.</p></div><x-table><thead><tr><th>Supplier</th><th class="text-end">Total Payable</th><th class="text-end">Current</th><th class="text-end">1–30</th><th class="text-end">31–60</th><th class="text-end">61–90</th><th class="text-end">90+</th><th>Oldest Due</th><th></th></tr></thead><tbody>@forelse($rows as $row)<tr><td class="fw-semibold">{{ $row->party_name }}</td><td class="text-end fw-semibold">{{ $money($row->total_outstanding) }}</td>@foreach($labels as $key => $label)<td class="text-end {{ (float) $row->{$key} > 0 ? 'text-'.$tones[$key] : 'tf-muted' }}">{{ $money($row->{$key}) }}</td>@endforeach<td>{{ $row->oldest_due ? \Illuminate\Support\Carbon::parse($row->oldest_due)->format('n/j/Y') : '—' }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('business.reports.supplier-aging.show', [$row->party_id] + request()->query()) }}">View</a></td></tr>@empty<tr><td colspan="9" class="text-center tf-muted py-5">No outstanding supplier payables match these filters.</td></tr>@endforelse</tbody></x-table>@if($rows->hasPages())<div class="px-3 py-3">{{ $rows->links('pagination::bootstrap-5') }}</div>@endif</section>
@endsection
