@extends('layouts.dashboard')
@section('page-title', 'New Sales Quotation')
@section('page-subtitle', 'Price a future sale without changing stock or accounts')
@section('content')
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('business.sales.quotations.store') }}" class="tf-card p-4" data-quotation-form>@csrf
<div class="row g-3 mb-4"><div class="col-md-4"><label class="form-label">Customer</label><select name="customer_id" class="form-select"><option value="">Walk-in / prospective customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->business_name ?: $customer->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Quotation Date</label><input name="quotation_date" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">Valid Until</label><input name="valid_until" type="date" class="form-control"></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option>Draft</option><option>Sent</option></select></div></div>
<x-table><thead><tr><th>Product</th><th style="width:130px">Qty</th><th style="width:160px">Unit Price</th><th style="width:130px">Total</th><th></th></tr></thead><tbody data-quotation-items><tr data-quotation-row><td><select name="items[0][product_id]" class="form-select" required><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}" data-price="{{ $product->wholesale_price }}">{{ $product->name }} ({{ $product->stock_quantity }} {{ $product->unit }})</option>@endforeach</select></td><td><input name="items[0][quantity]" type="number" min="1" value="1" class="form-control" required></td><td><input name="items[0][unit_price]" type="number" min="0" step="0.01" class="form-control" required></td><td class="text-end" data-quotation-total>Rs 0.00</td><td><button type="button" class="btn btn-outline-danger btn-sm" data-remove-quotation-row><i class="bi bi-x-lg"></i></button></td></tr></tbody></x-table>
<button type="button" class="btn btn-outline-primary btn-sm mt-3" data-add-quotation-row><i class="bi bi-plus-lg me-1"></i>Add item</button><div class="row g-3 mt-2"><div class="col-md-4"><label class="form-label">Discount</label><input name="discount_amount" type="number" min="0" step="0.01" value="0" class="form-control"></div><div class="col-md-4"><label class="form-label">Tax</label><input name="tax_amount" type="number" min="0" step="0.01" value="0" class="form-control"></div><div class="col-md-4"><label class="form-label">Notes</label><input name="notes" class="form-control"></div></div><div class="d-flex justify-content-between align-items-center mt-4"><a href="{{ route('business.sales.quotations.index') }}" class="btn btn-outline-secondary">Cancel</a><button class="btn btn-tf-primary">Save quotation</button></div></form>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const f=document.querySelector('[data-quotation-form]');if(!f)return;const b=f.querySelector('[data-quotation-items]'),t=b.querySelector('[data-quotation-row]').outerHTML,render=()=>b.querySelectorAll('[data-quotation-row]').forEach((r,i)=>{r.querySelectorAll('[name]').forEach(e=>e.name=e.name.replace(/items\[\d+\]/,'items['+i+']'));const s=r.querySelector('select'),q=r.querySelector('[name$="[quantity]"]'),p=r.querySelector('[name$="[unit_price]"]');if(s.value&&!p.value)p.value=s.selectedOptions[0].dataset.price||0;r.querySelector('[data-quotation-total]').textContent='Rs '+((+q.value||0)*(+p.value||0)).toFixed(2)});f.querySelector('[data-add-quotation-row]').onclick=()=>{b.insertAdjacentHTML('beforeend',t);const r=b.lastElementChild;r.querySelector('select').value='';r.querySelector('[name$="[unit_price]"]').value='';render()};b.addEventListener('input',render);b.addEventListener('change',render);b.addEventListener('click',e=>{const x=e.target.closest('[data-remove-quotation-row]');if(x&&b.children.length>1){x.closest('[data-quotation-row]').remove();render()}});render()});</script>@endpush
@endsection
