<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminNotificationController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\CompanyPermissionController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Business\BusinessDashboardController;
use App\Http\Controllers\Business\BusinessContextController;
use App\Http\Controllers\Business\AuditLogController;
use App\Http\Controllers\Business\CustomerController;
use App\Http\Controllers\Business\DeliveryController;
use App\Http\Controllers\Business\ExpenseController;
use App\Http\Controllers\Business\InventoryController;
use App\Http\Controllers\Business\InvoiceController;
use App\Http\Controllers\Business\KhataController;
use App\Http\Controllers\Business\OrderController;
use App\Http\Controllers\Business\PaymentController;
use App\Http\Controllers\Business\PosController;
use App\Http\Controllers\Business\ProductController;
use App\Http\Controllers\Business\ReportController;
use App\Http\Controllers\Business\StaffController;
use App\Http\Controllers\Business\StaffDashboardController;
use App\Http\Controllers\Business\SettingsController;
use App\Http\Controllers\Business\SupportController;
use App\Http\Controllers\Business\SupplierController;
use App\Http\Controllers\BusinessOnboardingController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashboardRedirectController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Retailer\RetailerController;
use Illuminate\Support\Facades\Route;

Route::view('/', 'public.home')->name('public.home');
Route::view('/features', 'public.features')->name('public.features');
Route::view('/pricing', 'public.pricing')->name('public.pricing');
Route::view('/contact', 'public.contact')->name('public.contact');
Route::view('/privacy-security', 'public.privacy-security')->name('privacy.security');
Route::get('/subscribe/{plan}', function (string $plan) {
    abort_unless(in_array($plan, ['basic', 'standard', 'premium'], true), 404);
    return view('public.subscribe', ['plan' => $plan]);
})->name('subscribe.plan');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.store');
    Route::get('/register', [AuthController::class, 'registerForm'])->name('register');
    Route::post('/register', [AuthController::class, 'register'])->name('register.store');
    Route::get('/forgot-password', [AuthController::class, 'forgotForm'])->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'sendResetLink'])->name('password.email');
    Route::get('/reset-password/{token}', [AuthController::class, 'resetForm'])->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,10')->name('password.update');
    Route::get('/otp-verification', [AuthController::class, 'otpForm'])->name('otp');
});

Route::get('/register-business', [BusinessOnboardingController::class, 'create'])->name('register.business');
Route::post('/register-business', [BusinessOnboardingController::class, 'store'])->name('register.business.store');

Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/dashboard', DashboardRedirectController::class)->name('dashboard.redirect');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::match(['post', 'put'], '/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::put('/profile/password', [ProfileController::class, 'password'])->name('profile.password');
    Route::post('/activity/heartbeat', [AdminController::class, 'heartbeat'])->name('activity.heartbeat');
    Route::get('/notifications', function () {
        return view('auth.notifications', ['notifications' => auth()->user()->notifications()->latest()->paginate(20)]);
    })->name('notifications.index');
    Route::prefix('business')->name('business.')->middleware(['super_admin.context', 'role:super_admin,business_owner,business_admin,business_sub_admin,manager,sales_staff,inventory_staff,accountant,delivery_staff,cashier,support_staff,custom_staff', 'business.approved', 'track.activity'])->group(function () {
        Route::get('/support', [SupportController::class, 'index'])->name('support');
        Route::post('/support', [SupportController::class, 'store'])->name('support.store');
    });
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:super_admin', 'track.activity'])->group(function () {
    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
    Route::get('/companies', [CompanyController::class, 'index'])->name('companies.index');
    Route::get('/companies/create', [CompanyController::class, 'create'])->name('companies.create');
    Route::post('/companies', [CompanyController::class, 'store'])->name('companies.store');
    Route::get('/companies/pending', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'pending'))->name('companies.pending');
    Route::get('/companies/approved', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'approved'))->name('companies.approved');
    Route::get('/companies/rejected', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'rejected'))->name('companies.rejected');
    Route::get('/companies/suspended', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'suspended'))->name('companies.suspended');
    Route::get('/companies/archived', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'archived'))->name('companies.archived');
    Route::get('/companies/{company}', [CompanyController::class, 'show'])->name('companies.show');
    Route::get('/companies/{company}/edit', [CompanyController::class, 'edit'])->name('companies.edit');
    Route::put('/companies/{company}', [CompanyController::class, 'update'])->name('companies.update');
    Route::patch('/companies/{company}/status', [CompanyController::class, 'updateStatus'])->name('companies.status');
    Route::patch('/companies/{company}/archive', [CompanyController::class, 'archive'])->name('companies.archive');
    Route::patch('/companies/{company}/restore', [CompanyController::class, 'restore'])->name('companies.restore');
    Route::delete('/companies/{company}', [CompanyController::class, 'destroy'])->name('companies.destroy');
    Route::post('/companies/{company}/open-dashboard', [CompanyController::class, 'openDashboard'])->name('companies.open-dashboard');
    Route::post('/company-context/return', [CompanyController::class, 'returnToDashboard'])->name('company-context.return');
    Route::post('/companies/{company}/owner/reset-password', [CompanyController::class, 'resetOwnerPassword'])->name('companies.owner.reset-password');
    Route::post('/companies/{company}/staff/{staff}/reset-password', [CompanyController::class, 'resetStaffPassword'])->name('companies.staff.reset-password');
    Route::get('/permissions/modules', [CompanyPermissionController::class, 'modules'])->name('permissions.modules');
    Route::get('/permissions/features', [CompanyPermissionController::class, 'features'])->name('permissions.features');
    Route::get('/permissions/actions', [CompanyPermissionController::class, 'actions'])->name('permissions.actions');
    Route::put('/permissions/company', [CompanyPermissionController::class, 'update'])->name('permissions.company.update');
    Route::get('/permissions/templates', [CompanyPermissionController::class, 'templates'])->name('permissions.templates');
    Route::post('/permissions/templates', [CompanyPermissionController::class, 'storeTemplate'])->name('permissions.templates.store');
    Route::post('/permissions/templates/{template}/apply', [CompanyPermissionController::class, 'applyTemplate'])->name('permissions.templates.apply');
    Route::get('/notifications-center', [AdminNotificationController::class, 'index'])->name('notifications.index');
    Route::get('/notifications-center/unread', fn (\Illuminate\Http\Request $request) => app(AdminNotificationController::class)->index($request, 'unread'))->name('notifications.unread');
    Route::get('/notifications-center/registrations', fn (\Illuminate\Http\Request $request) => app(AdminNotificationController::class)->index($request, 'registrations'))->name('notifications.registrations');
    Route::get('/notifications-center/alerts', fn (\Illuminate\Http\Request $request) => app(AdminNotificationController::class)->index($request, 'alerts'))->name('notifications.alerts');
    Route::patch('/notifications-center/{notification}/read', [AdminNotificationController::class, 'markRead'])->name('notifications.read');
    Route::patch('/notifications-center/read-all', [AdminNotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::get('/approvals/pending', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'pending'))->name('approvals.pending');
    Route::get('/approvals/history', [CompanyController::class, 'approvalHistory'])->name('approvals.history');
    Route::get('/approvals/history/{approvalLog}', [CompanyController::class, 'approvalHistoryShow'])->name('approvals.history.show');
    Route::get('/approvals/rejected', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'rejected'))->name('approvals.rejected');
    Route::get('/approvals/suspended', fn (\Illuminate\Http\Request $request) => app(CompanyController::class)->index($request, 'suspended'))->name('approvals.suspended');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.show');
    Route::get('/profile/settings', [ProfileController::class, 'edit'])->name('profile.settings');
    Route::get('/profile/password', [ProfileController::class, 'edit'])->name('profile.password');
    Route::get('/profile/security', fn () => view('super-admin.profile-security'))->name('profile.security');
    Route::get('/live-activity', [AdminController::class, 'liveActivity'])->name('live-activity');
    Route::get('/businesses', [AdminController::class, 'businesses'])->name('businesses');
    Route::get('/businesses/{business}', [AdminController::class, 'businessShow'])->name('businesses.show');
    Route::patch('/businesses/{business}/status', [AdminController::class, 'updateStatus'])->name('businesses.status');
    Route::get('/users', [AdminController::class, 'users'])->name('users');
    Route::patch('/users/{user}/status', [AdminController::class, 'updateUserStatus'])->name('users.status');
    Route::get('/subscriptions', [AdminController::class, 'subscriptions'])->name('subscriptions');
    Route::post('/subscription-plans', [AdminController::class, 'storePlan'])->name('subscription-plans.store');
    Route::patch('/subscription-plans/{plan}', [AdminController::class, 'updatePlan'])->name('subscription-plans.update');
    Route::delete('/subscription-plans/{plan}', [AdminController::class, 'destroyPlan'])->name('subscription-plans.destroy');
    Route::post('/subscriptions', [AdminController::class, 'activateSubscription'])->name('subscriptions.activate');
    Route::patch('/subscriptions/{subscription}', [AdminController::class, 'updateSubscription'])->name('subscriptions.update');
    Route::patch('/subscriptions/{subscription}/cancel', [AdminController::class, 'cancelSubscription'])->name('subscriptions.cancel');
    Route::delete('/subscriptions/{subscription}', [AdminController::class, 'destroySubscription'])->name('subscriptions.destroy');
    Route::get('/support-tickets', [AdminController::class, 'supportTickets'])->name('support-tickets');
    Route::patch('/support-tickets/{ticket}', [AdminController::class, 'updateTicket'])->name('support-tickets.update');
    Route::get('/categories', [AdminController::class, 'categories'])->name('categories');
    Route::post('/categories', [AdminController::class, 'storeCategory'])->name('categories.store');
    Route::get('/payments', [AdminController::class, 'payments'])->name('payments');
    Route::get('/notifications', [AdminController::class, 'notifications'])->name('notifications');
    Route::post('/notifications', [AdminController::class, 'storeAnnouncement'])->name('notifications.store');
    Route::get('/audit-logs', [AdminController::class, 'auditLogs'])->name('audit-logs');
    Route::get('/settings', [AdminController::class, 'settings'])->name('settings');
    Route::put('/settings', [AdminController::class, 'updateSettings'])->name('settings.update');
    Route::get('/business-reports', [AdminController::class, 'businessReports'])->name('business-reports');
    Route::get('/business-reports/{business}', [AdminController::class, 'businessReportShow'])->name('business-reports.show');
    Route::post('/business-reports/{report}/approve', [AdminController::class, 'approveReport'])->name('business-reports.approve');
    Route::post('/business-reports/{report}/reject', [AdminController::class, 'rejectReport'])->name('business-reports.reject');
    Route::get('/business-reports/{report}/pdf', [AdminController::class, 'reportPdf'])->name('business-reports.pdf');
});

Route::prefix('business')->name('business.')->middleware(['auth', 'super_admin.context', 'role:super_admin,business_owner,business_admin,business_sub_admin,manager,sales_staff,inventory_staff,accountant,delivery_staff,cashier,support_staff,custom_staff', 'business.approved', 'business.action', 'track.activity'])->group(function () {
    Route::get('/dashboard', BusinessDashboardController::class)->name('dashboard');
    Route::get('/context-profile', [BusinessContextController::class, 'profile'])->name('context.profile');
    Route::get('/context-notifications', [BusinessContextController::class, 'notifications'])->name('context.notifications');
    Route::patch('/products/{product}/low-stock-alert', [ProductController::class, 'updateLowStockAlert'])->name('products.low-stock-alert')->middleware('business.permission:Products');
    Route::get('/products-bulk', [ProductController::class, 'bulk'])->name('products.bulk')->middleware('business.permission:Products');
    Route::post('/products-bulk', [ProductController::class, 'bulkStore'])->name('products.bulk.store')->middleware('business.permission:Products');
    Route::get('/products-template.csv', [ProductController::class, 'csvTemplate'])->name('products.template')->middleware('business.permission:Products');
    Route::get('/products-export.csv', [ProductController::class, 'export'])->name('products.export')->middleware('business.permission:Products');
    Route::patch('/products/{product}/archive', [ProductController::class, 'archive'])->name('products.archive')->middleware('business.permission:Products');
    Route::patch('/products/{product}/restore', [ProductController::class, 'restore'])->name('products.restore')->middleware('business.permission:Products');
    Route::resource('products', ProductController::class)->middleware('business.permission:Products');
    Route::patch('/customers/{customer}/archive', [CustomerController::class, 'archive'])->name('customers.archive')->middleware('business.permission:Customers');
    Route::patch('/customers/{customer}/restore', [CustomerController::class, 'restore'])->name('customers.restore')->middleware('business.permission:Customers');
    Route::patch('/customers/{customer}/status', [CustomerController::class, 'updateStatus'])->name('customers.status')->middleware('business.permission:Customers');
    Route::delete('/customers/{customer}', [CustomerController::class, 'destroy'])->name('customers.destroy')->middleware('business.permission:Customers');
    Route::get('/customers/{customer}/statement', [CustomerController::class, 'statement'])->name('customers.statement')->middleware('business.permission:Customers');
    Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory')->middleware('business.permission:Inventory');
    Route::post('/inventory/adjust', [InventoryController::class, 'adjust'])->name('inventory.adjust')->middleware('business.permission:Inventory');
    Route::post('/inventory/transfer', [InventoryController::class, 'transfer'])->name('inventory.transfer')->middleware('business.permission:Inventory');
    Route::patch('/inventory/{inventory}/alert', [InventoryController::class, 'updateAlert'])->name('inventory.alert')->middleware('business.permission:Inventory');
    Route::resource('customers', CustomerController::class)->only(['index', 'store', 'show', 'update'])->middleware('business.permission:Customers');
    Route::resource('suppliers', SupplierController::class)->middleware('business.permission:Suppliers');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index')->middleware('business.permission:Orders');
    Route::get('/orders/create', [OrderController::class, 'create'])->name('orders.create')->middleware('business.permission:Orders');
    Route::post('/orders', [OrderController::class, 'store'])->name('orders.store')->middleware(['business.permission:Orders', 'company.permission:orders.create']);
    Route::post('/orders/{order}/assign-delivery', [OrderController::class, 'assignDelivery'])->name('orders.assignDelivery')->middleware(['business.permission:Deliveries', 'company.permission:orders.assign_delivery']);
    Route::get('/orders/{order}/edit', [OrderController::class, 'edit'])->name('orders.edit')->middleware('business.permission:Orders');
    Route::put('/orders/{order}', [OrderController::class, 'update'])->name('orders.update')->middleware(['business.permission:Orders', 'company.permission:orders.edit']);
    Route::patch('/orders/{order}/cancel', [OrderController::class, 'cancel'])->name('orders.cancel')->middleware(['business.permission:Orders', 'company.permission:orders.cancel']);
    Route::patch('/orders/{order}/void', [OrderController::class, 'void'])->name('orders.void')->middleware('business.permission:Orders');
    Route::delete('/orders/{order}', [OrderController::class, 'destroy'])->name('orders.destroy')->middleware('business.permission:Orders');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show')->middleware('business.permission:Orders');
    Route::patch('/orders/{order}/status', [OrderController::class, 'updateStatus'])->name('orders.status')->middleware(['business.permission:Orders', 'company.permission:orders.update_status']);
    Route::get('/pos', [PosController::class, 'index'])->name('pos.index')->middleware('business.permission:POS');
    Route::post('/pos/register/open', [PosController::class, 'openRegister'])->name('pos.register.open')->middleware('business.permission:POS');
    Route::patch('/pos/register/{register}/close', [PosController::class, 'closeRegister'])->name('pos.register.close')->middleware('business.permission:POS');
    Route::post('/pos/sales', [PosController::class, 'store'])->name('pos.sales.store')->middleware('business.permission:POS');
    Route::get('/pos/history', [PosController::class, 'history'])->name('pos.history')->middleware('business.permission:POS');
    Route::get('/pos/receipt/{order}', [PosController::class, 'receipt'])->name('pos.receipt')->middleware('business.permission:POS');
    Route::get('/pos/receipt/{order}/pdf', [PosController::class, 'receiptPdf'])->name('pos.receipt.pdf')->middleware('business.permission:POS');
    Route::get('/pos/receipt/{order}/pdf/download', [PosController::class, 'downloadReceiptPdf'])->name('pos.receipt.pdf.download')->middleware('business.permission:POS');
    Route::patch('/pos/{order}/void', [PosController::class, 'void'])->name('pos.void')->middleware('business.permission:POS');
    Route::get('/pos/returns/{order}', [PosController::class, 'returns'])->name('pos.returns')->middleware('business.permission:POS');
    Route::post('/pos/returns/{order}', [PosController::class, 'storeReturn'])->name('pos.returns.store')->middleware('business.permission:POS');
    Route::get('/pos/reports', [PosController::class, 'report'])->name('pos.report')->middleware('business.permission:POS');
    Route::get('/payments', [PaymentController::class, 'index'])->name('payments')->middleware('business.permission:Payments');
    Route::post('/payments', [PaymentController::class, 'store'])->name('payments.store')->middleware(['business.permission:Payments', 'company.permission:payments.create']);
    Route::get('/khata', [KhataController::class, 'index'])->name('khata')->middleware('business.permission:Khata');
    Route::post('/khata/journal-entries', [KhataController::class, 'storeJournal'])->name('khata.journal.store')->middleware('business.permission:Khata');
    Route::get('/deliveries', [DeliveryController::class, 'index'])->name('deliveries')->middleware('business.permission:Deliveries');
    Route::get('/deliveries/{delivery}', [DeliveryController::class, 'show'])->name('deliveries.show')->middleware('business.permission:Deliveries');
    Route::patch('/deliveries/{delivery}', [DeliveryController::class, 'update'])->name('deliveries.update')->middleware('business.permission:Deliveries');
    Route::patch('/deliveries/{delivery}/start', [DeliveryController::class, 'start'])->name('deliveries.start')->middleware('business.permission:Deliveries');
    Route::patch('/deliveries/{delivery}/deliver', [DeliveryController::class, 'deliver'])->name('deliveries.deliver')->middleware(['business.permission:Deliveries', 'company.permission:deliveries.upload_proof']);
    Route::patch('/deliveries/{delivery}/fail', [DeliveryController::class, 'fail'])->name('deliveries.fail')->middleware('business.permission:Deliveries');
    Route::patch('/deliveries/{delivery}/reopen', [DeliveryController::class, 'reopen'])->name('deliveries.reopen')->middleware('business.permission:Deliveries');
    Route::patch('/deliveries/{delivery}/cancel', [DeliveryController::class, 'cancel'])->name('deliveries.cancel')->middleware('business.permission:Deliveries');
    Route::get('/deliveries/{delivery}/sheet', [DeliveryController::class, 'sheet'])->name('deliveries.sheet')->middleware('business.permission:Deliveries');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index')->middleware('business.permission:Invoices');
    Route::get('/invoices/{order}', [InvoiceController::class, 'show'])->name('invoices.show')->middleware('business.permission:Invoices');
    Route::get('/invoices/{order}/pdf', [InvoiceController::class, 'pdf'])->name('invoices.pdf')->middleware('business.permission:Invoices');
    Route::get('/invoices/{order}/pdf/download', [InvoiceController::class, 'downloadPdf'])->name('invoices.pdf.download')->middleware('business.permission:Invoices');
    Route::patch('/invoice-records/{invoice}', [InvoiceController::class, 'update'])->name('invoices.update')->middleware('business.permission:Invoices');
    Route::patch('/invoice-records/{invoice}/issue', [InvoiceController::class, 'issue'])->name('invoices.issue')->middleware('business.permission:Invoices');
    Route::patch('/invoice-records/{invoice}/void', [InvoiceController::class, 'void'])->name('invoices.void')->middleware('business.permission:Invoices');
    Route::patch('/invoice-records/{invoice}/reissue', [InvoiceController::class, 'reissue'])->name('invoices.reissue')->middleware('business.permission:Invoices');
    Route::post('/invoice-records/{invoice}/credit-notes', [InvoiceController::class, 'creditNote'])->name('invoices.credit-notes.store')->middleware('business.permission:Invoices');
    Route::post('/expenses', [ExpenseController::class, 'store'])->name('expenses.store')->middleware('business.permission:Expenses');
    Route::get('/expenses', [ExpenseController::class, 'index'])->name('expenses.index')->middleware('business.permission:Expenses');
    Route::delete('/expenses/{expense}', [ExpenseController::class, 'destroy'])->name('expenses.destroy')->middleware('business.permission:Expenses');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports')->middleware('business.permission:Reports');
    Route::get('/reports/{type}/pdf', [ReportController::class, 'pdf'])->name('reports.pdf')->middleware('business.permission:Reports');
    Route::get('/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index')->middleware('business.permission:Audit Logs');
    Route::get('/audit-logs/live', [AuditLogController::class, 'live'])->name('audit-logs.live')->middleware('business.permission:Audit Logs');
    Route::get('/audit-logs/export/csv', [AuditLogController::class, 'exportCsv'])->name('audit-logs.export.csv')->middleware('business.permission:Audit Logs');
    Route::get('/audit-logs/export/pdf', [AuditLogController::class, 'exportPdf'])->name('audit-logs.export.pdf')->middleware('business.permission:Audit Logs');
    Route::get('/staff', [StaffController::class, 'index'])->name('staff')->middleware('role:super_admin,business_owner,business_admin');
    Route::post('/staff', [StaffController::class, 'store'])->name('staff.store')->middleware('role:super_admin,business_owner,business_admin');
    Route::get('/staff/{staff}', [StaffController::class, 'show'])->name('staff.show')->middleware('role:super_admin,business_owner,business_admin');
    Route::get('/staff/{staff}/edit', [StaffController::class, 'edit'])->name('staff.edit')->middleware('role:super_admin,business_owner,business_admin');
    Route::put('/staff/{staff}', [StaffController::class, 'update'])->name('staff.update')->middleware('role:super_admin,business_owner,business_admin');
    Route::patch('/staff/{staff}/status', [StaffController::class, 'updateStatus'])->name('staff.status')->middleware('role:super_admin,business_owner,business_admin');
    Route::patch('/staff/{staff}/reset-password', [StaffController::class, 'resetPassword'])->name('staff.reset-password')->middleware('role:super_admin,business_owner,business_admin');
    Route::patch('/staff/{staff}/archive', [StaffController::class, 'archive'])->name('staff.archive')->middleware('role:super_admin,business_owner,business_admin');
    Route::patch('/staff/{staff}/restore', [StaffController::class, 'restore'])->name('staff.restore')->middleware('role:super_admin,business_owner,business_admin');
    Route::delete('/staff/{staff}', [StaffController::class, 'destroy'])->name('staff.destroy')->middleware('role:super_admin,business_owner,business_admin');
    Route::get('/settings', [SettingsController::class, 'index'])->name('settings')->middleware('role:super_admin,business_owner');
    Route::put('/settings/business', [SettingsController::class, 'updateBusiness'])->name('settings.business')->middleware('role:super_admin,business_owner');
});

Route::prefix('staff')->name('staff.')->middleware(['auth', 'role:business_admin,business_sub_admin,manager,sales_staff,inventory_staff,accountant,delivery_staff,cashier,support_staff,custom_staff', 'business.approved', 'track.activity'])->group(function () {
    Route::get('/dashboard', StaffDashboardController::class)->name('dashboard');
});

Route::prefix('retailer')->name('retailer.')->middleware(['auth', 'role:retailer'])->group(function () {
    Route::get('/dashboard', [RetailerController::class, 'dashboard'])->name('dashboard');
    Route::get('/products', [RetailerController::class, 'products'])->name('products');
    Route::get('/cart', [RetailerController::class, 'cart'])->name('cart');
    Route::post('/cart/order', [RetailerController::class, 'placeOrder'])->name('cart.order');
    Route::get('/orders', [RetailerController::class, 'orders'])->name('orders');
    Route::get('/credit-balance', [RetailerController::class, 'creditBalance'])->name('credit-balance');
});
