@extends('layouts.dashboard')
@section('title', 'POS | TradeFlow')
@section('page-title', 'Point of Sale')
@section('page-subtitle', 'Counter sales, receipts, and register control')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

@if(!$register)
    <section class="tf-card p-4 mx-auto" style="max-width:680px"><div class="d-flex gap-3 align-items-center mb-3"><span class="tf-brand-mark bg-blue"><i class="bi bi-cash-register"></i></span><div><h2 class="h5 mb-1">Open POS Register</h2><p class="tf-muted mb-0">Record opening cash before processing counter sales.</p></div></div><form method="POST" action="{{ route('business.pos.register.open') }}" class="row g-3">@csrf<div class="col-md-6"><label class="form-label" for="opening_cash">Opening Cash</label><input id="opening_cash" name="opening_cash" type="number" min="0" step="0.01" value="0" class="form-control" required></div><div class="col-md-6"><label class="form-label" for="opening_note">Opening Note</label><input id="opening_note" name="opening_note" class="form-control"></div><div class="col-12">@companyCan('pos.open_register')<button class="btn btn-tf-primary"><i class="bi bi-unlock me-1"></i>Open Register</button>@endcompanyCan</div></form></section>
@else
    @php($categories = $products->pluck('category.name')->filter()->unique()->sort()->values())
    <section class="pos-workspace-header tf-card p-3 mb-3">
        <div class="pos-workspace-search"><div class="input-group"><span class="input-group-text"><i class="bi bi-upc-scan"></i></span><input id="pos-barcode" class="form-control" placeholder="Scan barcode or enter SKU" autocomplete="off" autofocus></div><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input id="pos-search" class="form-control" placeholder="Search product name, SKU, or barcode" autocomplete="off"></div></div>
        <div class="pos-workspace-meta"><span class="tf-badge tf-badge-success"><i class="bi bi-circle-fill me-1"></i>Register Open</span><span class="small tf-muted">Opening cash <strong>Rs {{ number_format($register->opening_cash, 2) }}</strong></span><span class="small tf-muted">Current invoice <strong data-pos-invoice-number>New sale</strong></span></div>
        <div class="pos-workspace-actions"><button type="button" class="btn btn-outline-secondary" id="pos-hold-sale"><i class="bi bi-pause-circle me-1"></i>Hold Sale</button><a href="{{ route('business.pos.history') }}" class="btn btn-outline-primary"><i class="bi bi-clock-history me-1"></i>Sales History</a>@companyCan('pos.close_register')<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#closeRegisterModal"><i class="bi bi-lock me-1"></i>Close Register</button>@endcompanyCan</div>
    </section>

    <form method="POST" action="{{ route('business.pos.sales.store') }}" data-pos-form data-pos-hold-key="tradeflow-pos-held-sale-{{ $register->business_id }}" data-custom-price="{{ app(\App\Services\CompanyPermissionService::class)->allowsUser(auth()->user(), 'pos.custom_price') ? '1' : '0' }}">@csrf
        <div class="row g-3 pos-workspace">
            <div class="col-xl-7 col-xxl-8"><section class="tf-card p-3 h-100 pos-products-panel">
                <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-0">Products</h2><small class="tf-muted">Click a product or scan its code to add it to the cart.</small></div><span class="small tf-muted" id="pos-product-count">{{ $products->count() }} products</span></div>
                <div class="pos-category-chips mb-3" id="pos-category-chips"><button type="button" class="btn btn-sm btn-tf-primary active" data-pos-category-chip="">All</button>@foreach($categories as $category)<button type="button" class="btn btn-sm btn-outline-secondary" data-pos-category-chip="{{ strtolower($category) }}">{{ $category }}</button>@endforeach</div>
                <div class="row g-3 pos-product-grid" id="pos-products">
                    @forelse($products as $product)
                        <div class="col-6 col-md-4 col-xxl-3 pos-product" data-search="{{ strtolower($product->name.' '.$product->sku.' '.$product->barcode) }}" data-category="{{ strtolower($product->category?->name ?? '') }}">
                            <button type="button" class="pos-product-card {{ $product->stock_quantity < 1 ? 'is-out-of-stock' : '' }}" data-product-id="{{ $product->id }}" data-product-name="{{ $product->name }}" data-price="{{ $product->retail_price }}" data-stock="{{ $product->stock_quantity }}" data-unit="{{ $product->unit }}" data-product-sku="{{ $product->sku }}" data-product-barcode="{{ $product->barcode }}" @disabled($product->stock_quantity < 1)>
                                @if($product->image)<img src="{{ asset('storage/'.$product->image) }}" class="pos-product-image" alt="{{ $product->name }}">@else<div class="pos-product-image pos-product-image-placeholder"><i class="bi bi-box-seam"></i></div>@endif
                                <span class="pos-product-name">{{ $product->name }}</span><span class="pos-product-code">{{ $product->sku ?: ($product->barcode ?: 'No code') }}</span><span class="pos-product-price">Rs {{ number_format($product->retail_price, 2) }}</span><span class="pos-product-stock {{ $product->stock_quantity > 0 ? 'text-success' : 'text-danger' }}">{{ $product->stock_quantity }} {{ $product->unit }} {{ $product->stock_quantity == 1 ? 'available' : 'available' }}</span>
                            </button>
                        </div>
                    @empty <div class="col-12 text-center tf-muted py-5">No active products are available for POS.</div>@endforelse
                </div>
            </section></div>

            <div class="col-xl-5 col-xxl-4"><section class="tf-card p-3 pos-cart-panel">
                <div class="d-flex align-items-center justify-content-between gap-2 mb-3"><div><h2 class="h5 mb-0">Current Cart</h2><small class="tf-muted">Items and payment preview</small></div><button type="button" class="btn btn-sm btn-outline-danger" id="pos-clear-cart"><i class="bi bi-trash me-1"></i>Clear Cart</button></div>
                <div class="pos-quick-entry border rounded p-2 mb-3"><div class="row g-2 align-items-end"><div class="col-md-6"><label class="form-label small">Add product</label><select id="pos-entry-product" class="form-select"><option value="">Search product</option>@foreach($products as $product)<option value="{{ $product->id }}" data-name="{{ $product->name }}" data-price="{{ $product->retail_price }}" data-stock="{{ $product->stock_quantity }}" data-unit="{{ $product->unit }}" data-sku="{{ $product->sku }}" data-barcode="{{ $product->barcode }}" @disabled($product->stock_quantity < 1)>{{ $product->name }}</option>@endforeach</select></div><div class="col-3"><label class="form-label small">Stock</label><input id="pos-entry-stock" class="form-control" readonly></div><div class="col-3"><label class="form-label small">Qty</label><input id="pos-entry-qty" type="number" min="1" value="1" class="form-control"></div><div class="col-8"><label class="form-label small">Unit Price</label><input id="pos-entry-price" class="form-control" readonly></div><div class="col-4 d-grid"><button type="button" id="pos-entry-add" class="btn btn-tf-primary" aria-label="Add item"><i class="bi bi-plus-lg me-1"></i>Add</button></div></div><div id="pos-entry-error" class="invalid-feedback d-block d-none mt-2"></div></div>
                <div class="mb-3"><label class="form-label" for="pos-customer">Customer</label><select name="customer_id" id="pos-customer" class="form-select"><option value="walk_in">Walk-in Customer</option><option value="new">Create New Customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->display_name }}{{ $customer->business_name ? ' — '.$customer->business_name : '' }}{{ $customer->phone ? ' - '.$customer->phone : '' }}</option>@endforeach</select></div>
                <div id="pos-new-customer" class="row g-2 mb-3 d-none"><div class="col-md-6"><input name="new_customer_name" class="form-control" placeholder="Customer name"></div><div class="col-md-6"><input name="new_customer_phone" class="form-control" placeholder="Phone"></div><div class="col-md-6"><input name="new_customer_city" class="form-control" placeholder="City"></div><div class="col-md-6"><input name="new_customer_address" class="form-control" placeholder="Address"></div></div>
                <div id="pos-cart" class="pos-cart-table mb-3"><p class="tf-muted text-center py-4 mb-0">Add products to start a sale.</p></div>
                <div class="row g-2 border-top pt-3"><div class="col-6"><label class="form-label" for="pos-discount-value">Discount</label><div class="input-group"><select name="discount_type" id="pos-discount-type" class="form-select"><option value="percentage">%</option><option value="fixed">Rs</option></select><input name="discount_value" id="pos-discount-value" type="number" min="0" step="0.01" value="0" class="form-control"></div></div><div class="col-6"><label class="form-label" for="pos-tax-rate">Tax %</label><input name="tax_rate" id="pos-tax-rate" type="number" min="0" max="100" step="0.01" value="0" class="form-control"></div><div class="col-12"><label class="form-label" for="pos-payment-mode">Payment Type</label><select name="payment_mode" id="pos-payment-mode" class="form-select"><option value="cash">Cash Sale</option>@companyCan('pos.credit_sale')<option value="credit">Credit / Khata Sale</option>@endcompanyCan @companyCan('pos.split_payment')<option value="split">Split Payment</option>@endcompanyCan</select></div><div class="col-12" id="pos-payments"></div><div class="col-12 d-none" id="pos-add-payment-wrap">@companyCan('pos.split_payment')<button type="button" class="btn btn-sm btn-outline-primary" id="pos-add-payment"><i class="bi bi-plus-lg me-1"></i>Add Payment</button>@endcompanyCan</div></div>
                <div class="pos-totals mt-3"><div><span>Subtotal</span><strong id="pos-subtotal">Rs 0.00</strong></div><div><span>Discount</span><strong id="pos-discount">Rs 0.00</strong></div><div><span>Tax</span><strong id="pos-tax">Rs 0.00</strong></div><div><span>Paid Amount</span><strong id="pos-paid">Rs 0.00</strong></div><div><span>Due / Balance</span><strong id="pos-balance">Rs 0.00</strong></div><div><span>Change</span><strong id="pos-change">Rs 0.00</strong></div><div class="pos-grand-total"><span>Grand Total</span><strong id="pos-total">Rs 0.00</strong></div></div>
                @companyCan('pos.create_sale')<button type="submit" id="pos-complete-sale" class="btn btn-tf-primary w-100 mt-3" disabled><i class="bi bi-check2-circle me-1"></i>Complete Sale</button>@endcompanyCan
            </section></div>
        </div>
    </form>

    <div class="modal fade" id="closeRegisterModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('business.pos.register.close', $register) }}">@csrf @method('PATCH')<div class="modal-header"><h2 class="h5 modal-title">Close POS Register</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><label class="form-label" for="closing_cash">Closing Cash</label><input id="closing_cash" name="closing_cash" type="number" min="0" step="0.01" class="form-control" required><label class="form-label mt-3" for="closing_note">Closing Note</label><textarea id="closing_note" name="closing_note" class="form-control" rows="3"></textarea></div><div class="modal-footer"><button class="btn btn-tf-primary">Close Register</button></div></form></div></div></div>
@endif
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', () => {
    const form = document.querySelector('[data-pos-form]');
    if (!form || form.dataset.posInitialized === 'true') return;
    form.dataset.posInitialized = 'true';
    const products = document.getElementById('pos-products'), cartElement = document.getElementById('pos-cart'), paymentsElement = document.getElementById('pos-payments'), paymentMode = document.getElementById('pos-payment-mode'), completeButton = document.getElementById('pos-complete-sale'), holdButton = document.getElementById('pos-hold-sale'), holdKey = form.dataset.posHoldKey, customPrice = form.dataset.customPrice === '1';
    const barcode = document.getElementById('pos-barcode'), search = document.getElementById('pos-search'), entryProduct = document.getElementById('pos-entry-product'), entryStock = document.getElementById('pos-entry-stock'), entryQuantity = document.getElementById('pos-entry-qty'), entryPrice = document.getElementById('pos-entry-price'), entryError = document.getElementById('pos-entry-error');
    const cart = new Map(); let editingProductId = null, activeCategory = '';
    const money = value => 'Rs ' + Number(value || 0).toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2});
    const productFromButton = button => ({id:Number(button.dataset.productId), name:button.dataset.productName, price:Number(button.dataset.price), stock:Number(button.dataset.stock), unit:button.dataset.unit || 'Piece', sku:button.dataset.productSku || '', barcode:button.dataset.productBarcode || '', quantity:1});
    const syncSelect = select => window.syncTradeFlowTomSelect?.(select);
    const focusBarcode = () => setTimeout(() => barcode?.focus(), 0);
    const selectedOption = () => entryProduct?.selectedOptions[0];
    const paymentRow = index => '<div class="row g-2 payment-row mt-1"><div class="col-5"><select name="payments[' + index + '][method]" class="form-select"><option>Cash</option><option>Bank Transfer</option><option>JazzCash Manual</option><option>Easypaisa Manual</option><option>Cheque</option></select></div><div class="col-4"><input name="payments[' + index + '][amount]" type="number" min="0" step="0.01" class="form-control pos-payment-amount" placeholder="Paid amount"></div><div class="col-3"><input name="payments[' + index + '][reference_number]" class="form-control" placeholder="Reference"></div></div>';
    function totals() { const subtotal = [...cart.values()].reduce((sum,item) => sum + item.price * item.quantity, 0); const discountValue = Math.max(0, Number(document.getElementById('pos-discount-value').value || 0)); const discount = document.getElementById('pos-discount-type').value === 'percentage' ? subtotal * Math.min(100,discountValue) / 100 : Math.min(subtotal,discountValue); const tax = (subtotal-discount) * Math.max(0,Number(document.getElementById('pos-tax-rate').value || 0)) / 100; return {subtotal,discount,tax,total:subtotal-discount+tax}; }
    function updateSummary(current) { let paid = paymentMode.value === 'credit' ? 0 : [...paymentsElement.querySelectorAll('.pos-payment-amount')].reduce((sum,input) => sum + Math.max(0,Number(input.value || 0)),0); if (paymentMode.value === 'cash') paid = current.total; document.getElementById('pos-subtotal').textContent=money(current.subtotal); document.getElementById('pos-discount').textContent=money(current.discount); document.getElementById('pos-tax').textContent=money(current.tax); document.getElementById('pos-total').textContent=money(current.total); document.getElementById('pos-paid').textContent=money(paid); document.getElementById('pos-balance').textContent=money(Math.max(0,current.total-paid)); document.getElementById('pos-change').textContent=money(Math.max(0,paid-current.total)); }
    function syncEntry() { const option = selectedOption(); if (!option?.value) { entryStock.value=''; entryPrice.value=''; return; } entryStock.value=`${option.dataset.stock} ${option.dataset.unit || ''}`; entryPrice.value=option.dataset.price || 0; }
    function resetEntry() { editingProductId=null; entryProduct.value=''; entryQuantity.value=1; entryPrice.value=''; entryStock.value=''; entryError.classList.add('d-none'); syncSelect(entryProduct); focusBarcode(); }
    function render() { const current=totals(); cartElement.innerHTML=cart.size ? '<div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>#</th><th>Product</th><th>Quantity</th><th>Unit Price</th><th>Discount</th><th>Line Total</th><th></th></tr></thead><tbody>'+[...cart.values()].map((item,index)=>'<tr><td>'+(index+1)+'</td><td><strong>'+item.name+'</strong><small class="d-block tf-muted">'+(item.sku || item.barcode || '')+'</small><input type="hidden" name="items['+index+'][product_id]" value="'+item.id+'"></td><td><div class="input-group input-group-sm pos-quantity-control"><button type="button" class="btn btn-outline-secondary" data-cart-decrease="'+item.id+'" aria-label="Decrease quantity">−</button><input type="number" min="1" max="'+item.stock+'" class="form-control text-center" value="'+item.quantity+'" data-cart-quantity="'+item.id+'"><button type="button" class="btn btn-outline-secondary" data-cart-increase="'+item.id+'" aria-label="Increase quantity">+</button></div><input type="hidden" name="items['+index+'][quantity]" value="'+item.quantity+'"></td><td>'+money(item.price)+'<input type="hidden" name="items['+index+'][price]" value="'+item.price+'"></td><td>Rs 0.00</td><td><strong>'+money(item.price*item.quantity)+'</strong></td><td><button type="button" class="btn btn-sm btn-outline-danger" data-cart-remove="'+item.id+'" aria-label="Remove '+item.name+'"><i class="bi bi-trash"></i></button></td></tr>').join('')+'</tbody></table></div>' : '<p class="tf-muted text-center py-4 mb-0">Add products to start a sale.</p>'; if (!paymentsElement.children.length) paymentsElement.innerHTML=paymentRow(0); const credit=paymentMode.value==='credit'; paymentsElement.querySelectorAll('input,select').forEach(input=>input.disabled=credit); document.getElementById('pos-add-payment-wrap').classList.toggle('d-none',paymentMode.value!=='split'); if(paymentMode.value==='cash'){const cash=paymentsElement.querySelector('.pos-payment-amount');if(cash)cash.value=current.total.toFixed(2);} updateSummary(current); if(completeButton)completeButton.disabled=cart.size===0; }
    function addProduct(product) { if(!product.id || product.stock<1)return; const existing=cart.get(product.id); if(existing){ existing.quantity=Math.min(existing.stock,Number(product.quantity || 1)+(editingProductId===product.id?0:existing.quantity)); existing.price=customPrice?Number(product.price || existing.price):existing.price; }else cart.set(product.id,product); render(); }
    function filterProducts() { const term=search.value.trim().toLowerCase(); let visible=0; products.querySelectorAll('.pos-product').forEach(card=>{const show=card.dataset.search.includes(term)&&(!activeCategory||card.dataset.category===activeCategory);card.classList.toggle('d-none',!show);if(show)visible++;});document.getElementById('pos-product-count').textContent=visible+' product'+(visible===1?'':'s'); }
    function findExact(code){const query=code.trim().toLowerCase();return [...products.querySelectorAll('[data-product-id]')].find(item=>item.dataset.productBarcode.toLowerCase()===query||item.dataset.productSku.toLowerCase()===query||item.dataset.productName.toLowerCase()===query);}
    function holdState(){return {cart:[...cart.values()],customer:document.getElementById('pos-customer').value,discountType:document.getElementById('pos-discount-type').value,discountValue:document.getElementById('pos-discount-value').value,taxRate:document.getElementById('pos-tax-rate').value,paymentMode:paymentMode.value,payments:[...paymentsElement.querySelectorAll('.payment-row')].map(row=>({method:row.querySelector('select').value,amount:row.querySelector('.pos-payment-amount').value,reference:row.querySelector('[name$="[reference_number]"]').value})),newCustomer:['new_customer_name','new_customer_phone','new_customer_city','new_customer_address'].reduce((values,name)=>({...values,[name]:form.querySelector(`[name="${name}"]`)?.value || ''}),{})};}
    function refreshHoldButton(){const held=sessionStorage.getItem(holdKey);holdButton.innerHTML=held?'<i class="bi bi-play-circle me-1"></i>Resume Held Sale':'<i class="bi bi-pause-circle me-1"></i>Hold Sale';}
    function restoreHeldSale(){try{const state=JSON.parse(sessionStorage.getItem(holdKey)||'null');if(!state)return;cart.clear();(state.cart||[]).forEach(item=>cart.set(Number(item.id),item));['pos-discount-type','pos-discount-value','pos-tax-rate'].forEach((id,index)=>document.getElementById(id).value=[state.discountType,state.discountValue,state.taxRate][index] ?? document.getElementById(id).value);paymentMode.value=state.paymentMode || 'cash';document.getElementById('pos-customer').value=state.customer || 'walk_in';syncSelect(document.getElementById('pos-customer'));syncSelect(paymentMode);Object.entries(state.newCustomer || {}).forEach(([name,value])=>{const input=form.querySelector(`[name="${name}"]`);if(input)input.value=value;});document.getElementById('pos-new-customer').classList.toggle('d-none',(state.customer||'walk_in')!=='new');paymentsElement.innerHTML=(state.payments||[]).map((payment,index)=>{const wrapper=document.createElement('div');wrapper.innerHTML=paymentRow(index);const row=wrapper.firstElementChild;row.querySelector('select').value=payment.method;row.querySelector('.pos-payment-amount').value=payment.amount;row.querySelector('[name$="[reference_number]"]').value=payment.reference;return row.outerHTML;}).join('')||paymentRow(0);sessionStorage.removeItem(holdKey);render();refreshHoldButton();focusBarcode();}catch(_){sessionStorage.removeItem(holdKey);refreshHoldButton();}}
    products.addEventListener('click',event=>{const button=event.target.closest('[data-product-id]');if(button&&!button.disabled&&products.contains(button))addProduct(productFromButton(button));});
    document.querySelectorAll('[data-pos-category-chip]').forEach(chip=>chip.addEventListener('click',()=>{activeCategory=chip.dataset.posCategoryChip;document.querySelectorAll('[data-pos-category-chip]').forEach(item=>{item.classList.toggle('btn-tf-primary',item===chip);item.classList.toggle('btn-outline-secondary',item!==chip);item.classList.toggle('active',item===chip);});filterProducts();}));
    entryProduct.addEventListener('change',syncEntry);entryQuantity.addEventListener('input',syncEntry);document.getElementById('pos-entry-add').addEventListener('click',()=>{const option=selectedOption(),stock=Number(option?.dataset.stock||0),quantity=Number(entryQuantity.value||0);if(!option?.value||quantity<1||quantity>stock){entryError.textContent=!option?.value?'Select a product.':'Insufficient stock. Only '+stock+' units are available.';entryError.classList.remove('d-none');return;}if(editingProductId&&editingProductId!==Number(option.value))cart.delete(editingProductId);addProduct({id:Number(option.value),name:option.dataset.name,price:Number(option.dataset.price),stock,unit:option.dataset.unit||'Piece',sku:option.dataset.sku||'',barcode:option.dataset.barcode||'',quantity});resetEntry();});
    barcode.addEventListener('keydown',event=>{if(event.key!=='Enter')return;event.preventDefault();const button=findExact(barcode.value);if(button){addProduct(productFromButton(button));barcode.value='';}focusBarcode();});search.addEventListener('input',filterProducts);search.addEventListener('keydown',event=>{if(event.key!=='Enter')return;const button=findExact(search.value);if(!button)return;event.preventDefault();addProduct(productFromButton(button));search.value='';filterProducts();focusBarcode();});
    cartElement.addEventListener('click',event=>{const remove=event.target.closest('[data-cart-remove]'),increase=event.target.closest('[data-cart-increase]'),decrease=event.target.closest('[data-cart-decrease]'),id=Number(remove?.dataset.cartRemove||increase?.dataset.cartIncrease||decrease?.dataset.cartDecrease),item=cart.get(id);if(!item)return;if(increase){item.quantity=Math.min(item.stock,item.quantity+1);render();return;}if(decrease){item.quantity=Math.max(1,item.quantity-1);render();return;}if(remove){cart.delete(id);render();}});cartElement.addEventListener('input',event=>{const id=Number(event.target.dataset.cartQuantity),item=cart.get(id);if(!item)return;item.quantity=Math.max(1,Math.min(item.stock,parseInt(event.target.value||'1',10)||1));render();});
    paymentsElement.addEventListener('input',()=>updateSummary(totals()));document.getElementById('pos-add-payment')?.addEventListener('click',()=>{paymentsElement.insertAdjacentHTML('beforeend',paymentRow(paymentsElement.querySelectorAll('.payment-row').length));window.initTradeFlowTomSelect?.(paymentsElement);});document.getElementById('pos-customer').addEventListener('change',event=>document.getElementById('pos-new-customer').classList.toggle('d-none',event.target.value!=='new'));document.getElementById('pos-clear-cart').addEventListener('click',()=>{cart.clear();render();focusBarcode();});['pos-discount-value','pos-discount-type','pos-tax-rate','pos-payment-mode'].forEach(id=>{const input=document.getElementById(id);input.addEventListener('input',render);input.addEventListener('change',render);});
    holdButton.addEventListener('click',()=>{if(sessionStorage.getItem(holdKey)){restoreHeldSale();return;}if(!cart.size){window.Swal?.fire({icon:'info',title:'Cart is empty',text:'Add at least one product before holding this sale.'});return;}sessionStorage.setItem(holdKey,JSON.stringify(holdState()));cart.clear();form.reset();paymentsElement.innerHTML='';document.getElementById('pos-new-customer').classList.add('d-none');syncSelect(entryProduct);syncSelect(document.getElementById('pos-customer'));syncSelect(document.getElementById('pos-discount-type'));syncSelect(paymentMode);render();refreshHoldButton();focusBarcode();window.Swal?.fire({icon:'success',title:'Sale held',text:'The cart is saved for this browser session and can be resumed from POS.'});});
    form.addEventListener('submit',event=>{if(!cart.size){event.preventDefault();window.Swal?.fire({icon:'info',title:'Cart is empty',text:'Add at least one product before completing this sale.'});return;}if(!form.checkValidity())return;if(form.dataset.submitting==='1'){event.preventDefault();return;}form.dataset.submitting='1';sessionStorage.removeItem(holdKey);if(completeButton){completeButton.disabled=true;completeButton.innerHTML='<span class="spinner-border spinner-border-sm me-1"></span>Completing Sale';}});
    syncEntry();render();refreshHoldButton();focusBarcode();
});
</script>
@endpush
