@extends('layouts.dashboard')
@section('page-title', 'Company Details')
@section('page-subtitle', $company->business_name)
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

<div class="d-flex flex-wrap gap-2 mb-4">
    <form method="POST" action="{{ route('admin.companies.open-dashboard', $company) }}">@csrf<button class="btn btn-tf-primary"><i class="bi bi-box-arrow-up-right me-1"></i>Open Business Workspace</button></form>
    <a class="btn btn-outline-primary" href="{{ route('admin.companies.edit', $company) }}"><i class="bi bi-pencil me-1"></i>Edit Company</a>
    <a class="btn btn-outline-primary" href="{{ route('admin.permissions.index', ['company_id' => $company->id]) }}"><i class="bi bi-shield-lock me-1"></i>Manage Permissions</a>
    <a class="btn btn-outline-primary" href="{{ route('admin.business-detail-change-requests.index', ['business_id' => $company->id]) }}"><i class="bi bi-pencil-square me-1"></i>Review Detail Requests</a>
    <a class="btn btn-outline-primary" href="{{ route('admin.subscriptions', ['business_id' => $company->id]) }}"><i class="bi bi-credit-card me-1"></i>Manage Subscription</a>
    @if(strtolower($company->status) !== 'archived')
        <form method="POST" action="{{ route('admin.companies.archive', $company) }}">@csrf @method('PATCH')<button class="btn btn-outline-warning">Archive</button></form>
        <form method="POST" action="{{ route('admin.companies.destroy', $company) }}" data-tf-company-delete data-company-name="{{ $company->business_name }}">@csrf @method('DELETE')<button class="btn btn-outline-danger">Permanently Delete Company</button></form>
    @else
        <form method="POST" action="{{ route('admin.companies.restore', $company) }}">@csrf @method('PATCH')<button class="btn btn-outline-success">Restore</button></form>
    @endif
</div>

<div class="row g-4">
    <div class="col-lg-8">
        <div class="tf-card p-4"><h2 class="h5 mb-3">Company Overview</h2><div class="row g-3">@foreach(['Company Name' => $company->business_name, 'Owner' => $company->owner?->name, 'Email' => $company->owner?->email, 'Phone' => $company->phone, 'Business Type' => $company->business_type, 'Category' => $company->category, 'City' => $company->city, 'Created At' => optional($company->created_at)->format('d M, Y h:i A')] as $label => $value)<div class="col-md-6"><div class="border rounded p-3"><small class="tf-muted">{{ $label }}</small><strong class="d-block">{{ $value ?: '—' }}</strong></div></div>@endforeach</div></div>

        @php($workspaceModules = collect(['dashboard' => ['Dashboard', 'business.dashboard'], 'products' => ['Products', 'business.products.index'], 'inventory' => ['Inventory', 'business.inventory'], 'suppliers' => ['Suppliers', 'business.suppliers.index'], 'purchases' => ['Purchases', 'business.purchases.index'], 'purchase_returns' => ['Purchase Returns', 'business.purchase-returns.index'], 'customers' => ['Customers', 'business.customers.index'], 'sales' => ['Sales', 'business.sales.index'], 'sales_returns' => ['Sales Returns', 'business.sales.returns.index'], 'pos' => ['POS', 'business.pos.index'], 'deliveries' => ['Deliveries', 'business.deliveries'], 'accounting' => ['Accounting / Ledger', 'business.khata'], 'expenses' => ['Expenses', 'business.expenses.index'], 'reports' => ['Reports', 'business.reports'], 'staff' => ['Roles & Users', 'business.staff'], 'audit_logs' => ['Audit Logs', 'business.audit-logs.index'], 'settings' => ['Settings', 'business.settings']])->filter(fn ($workspace, $module) => app(\App\Services\CompanyPermissionService::class)->allowsUser(auth()->user(), $module.'.view', $company)))
        <div class="tf-card p-4 mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Company Workspace</h2><small class="tf-muted">Only modules enabled for this company can be opened.</small></div><div class="row g-2">@forelse($workspaceModules as [$label, $destination])<div class="col-md-4"><form method="POST" action="{{ route('admin.companies.open-dashboard', $company) }}">@csrf<input type="hidden" name="destination" value="{{ $destination }}"><button class="btn btn-outline-primary w-100 text-start">{{ $label }}</button></form></div>@empty<div class="col-12"><p class="tf-muted mb-0">No modules are enabled for this company.</p></div>@endforelse</div></div>

        <div class="tf-card p-4 mt-4"><h2 class="h5">Staff Accounts</h2><x-table><thead><tr><th>Name</th><th>Role</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($company->users->where('id', '!=', $company->owner_id) as $staff)<tr><td>{{ $staff->name }}</td><td>{{ str_replace('_', ' ', $staff->role) }}</td><td>{{ $staff->email }}</td><td>{{ ucfirst($staff->status) }}</td><td><button class="btn btn-sm btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#reset-staff-{{ $staff->id }}">Reset Password</button></td></tr><tr class="collapse" id="reset-staff-{{ $staff->id }}"><td colspan="5"><form method="POST" action="{{ route('admin.companies.staff.reset-password', [$company, $staff]) }}" class="row g-2">@csrf<div class="col-md-5"><input type="password" name="password" class="form-control" placeholder="New password" required></div><div class="col-md-5"><input type="password" name="password_confirmation" class="form-control" placeholder="Confirm password" required></div><div class="col-md-2 d-grid"><button class="btn btn-tf-primary">Save</button></div></form></td></tr>@empty<tr><td colspan="5" class="text-center tf-muted py-4">No staff accounts found.</td></tr>@endforelse</tbody></x-table></div>

        <div class="tf-card p-4 mt-4"><h2 class="h5">Recent Activity and Login History</h2><x-table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Module</th></tr></thead><tbody>@forelse($loginHistory as $entry)<tr><td><x-date-time :value="$entry->occurred_at" /></td><td>{{ $entry->actor?->name ?? 'System' }}</td><td>{{ $entry->description ?: $entry->action }}</td><td>{{ $entry->module }}</td></tr>@empty<tr><td colspan="4" class="text-center tf-muted py-4">No activity recorded.</td></tr>@endforelse</tbody></x-table><div class="d-flex flex-wrap gap-2 mt-3"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.audit-logs', ['business_id' => $company->id]) }}">View Audit Logs</a><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.live-activity', ['business_id' => $company->id]) }}">View Activity Logs</a><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.notifications.index') }}">View Notifications</a></div></div>

        <div class="tf-card p-4 mt-4"><h2 class="h5">Approval History</h2><x-table><thead><tr><th>From</th><th>To</th><th>Note</th><th>Changed By</th><th>When</th></tr></thead><tbody>@forelse($company->approvalLogs as $history)<tr><td>{{ ucfirst($history->old_status ?: '—') }}</td><td>{{ ucfirst($history->new_status) }}</td><td>{{ $history->note ?: '—' }}</td><td>{{ $history->changedBy?->name ?: 'System / Public' }}</td><td><x-date-time :value="$history->changed_at" /></td></tr>@empty<tr><td colspan="5" class="text-center tf-muted">No approval changes yet.</td></tr>@endforelse</tbody></x-table></div>
    </div>
    <div class="col-lg-4">
        <div class="tf-card p-4"><h2 class="h5">Approval Control</h2><p class="tf-muted">Current status: <strong>{{ $company->status }}</strong></p><form method="POST" action="{{ route('admin.companies.status', $company) }}">@csrf @method('PATCH')<label class="form-label">Select Status</label><select name="status" class="form-select mb-3">@foreach(['pending' => 'Pending', 'approved' => 'Approve / Activate', 'rejected' => 'Reject', 'suspended' => 'Suspend'] as $value => $label)<option value="{{ $value }}" @selected(strtolower($company->status) === $value)>{{ $label }}</option>@endforeach</select><label class="form-label">Admin Note</label><textarea name="admin_note" class="form-control mb-3" rows="3" placeholder="Reason or follow-up note"></textarea><button class="btn btn-tf-primary w-100">Save Status</button></form></div>
        <div class="tf-card p-4 mt-4"><h2 class="h5">Business Owner</h2><p class="mb-1"><strong>{{ $company->owner?->name ?? '—' }}</strong></p><p class="tf-muted small">{{ $company->owner?->email }}</p><button class="btn btn-outline-primary w-100" data-bs-toggle="collapse" data-bs-target="#owner-reset">Reset Owner Password</button><div class="collapse mt-3" id="owner-reset"><form method="POST" action="{{ route('admin.companies.owner.reset-password', $company) }}" class="d-grid gap-3">@csrf<div><label for="owner-reset-current" class="form-label">Current Password</label><div class="input-group"><input id="owner-reset-current" type="password" name="current_password" class="form-control @error('current_password') is-invalid @enderror" autocomplete="current-password" required><button class="btn btn-outline-secondary tf-password-toggle" type="button" data-tf-password-toggle="#owner-reset-current" data-tf-password-icon="#owner-reset-current-icon" aria-label="Show current password"><i id="owner-reset-current-icon" class="bi bi-eye"></i></button></div>@error('current_password')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div><label for="owner-reset-new" class="form-label">New Password</label><div class="input-group"><input id="owner-reset-new" type="password" name="password" class="form-control @error('password') is-invalid @enderror" autocomplete="new-password" required><button class="btn btn-outline-secondary tf-password-toggle" type="button" data-tf-password-toggle="#owner-reset-new" data-tf-password-icon="#owner-reset-new-icon" aria-label="Show new password"><i id="owner-reset-new-icon" class="bi bi-eye"></i></button></div>@error('password')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div><label for="owner-reset-confirm" class="form-label">Confirm New Password</label><div class="input-group"><input id="owner-reset-confirm" type="password" name="password_confirmation" class="form-control" autocomplete="new-password" required><button class="btn btn-outline-secondary tf-password-toggle" type="button" data-tf-password-toggle="#owner-reset-confirm" data-tf-password-icon="#owner-reset-confirm-icon" aria-label="Show confirm new password"><i id="owner-reset-confirm-icon" class="bi bi-eye"></i></button></div></div><small class="tf-muted">Use at least 8 characters, including uppercase, lowercase, number, and special character.</small><button class="btn btn-tf-primary">Reset Password</button></form></div></div>
        <div class="tf-card p-4 mt-4"><h2 class="h5">Verification Documents</h2>@forelse($company->documents as $document)<a class="d-block border rounded p-2 mb-2" href="{{ asset('storage/'.$document->file_path) }}" target="_blank">{{ str_replace('_', ' ', ucfirst($document->document_type)) }}</a>@empty<p class="tf-muted mb-0">No documents uploaded.</p>@endforelse</div>
    </div>
</div>
@endsection
