@extends('layouts.dashboard')
@section('page-title', 'New Purchase Order')
@section('page-subtitle', 'Create a supplier purchase order; inventory updates when goods are received')
@section('content')
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('business.purchases.store') }}" class="tf-card p-4" data-purchase-form>@csrf
<div class="row g-3 mb-4"><div class="col-md-4"><label class="form-label">Supplier</label><select name="supplier_id" class="form-select" required autofocus><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id') == $supplier->id)>{{ $supplier->supplier_name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Supplier Invoice / Reference</label><input name="supplier_invoice_number" value="{{ old('supplier_invoice_number') }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Purchase date</label><input name="purchase_date" type="datetime-local" value="{{ old('purchase_date', now()->format('Y-m-d\\TH:i')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Discount amount</label><input name="discount_amount" type="number" min="0" step="0.01" value="{{ old('discount_amount', 0) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Tax amount</label><input name="tax_amount" type="number" min="0" step="0.01" value="{{ old('tax_amount', 0) }}" class="form-control"></div><div class="col-12"><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="2">{{ old('notes') }}</textarea></div></div>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Purchase items</h2><button type="button" class="btn btn-sm btn-outline-primary" data-add-purchase-row><i class="bi bi-plus-lg me-1"></i>Add item</button></div>
<x-table><thead><tr><th>Product</th><th style="width:140px">Quantity</th><th style="width:180px">Unit cost</th><th style="width:160px">Line total</th><th></th></tr></thead><tbody data-purchase-items><tr data-purchase-row><td><select name="items[0][product_id]" class="form-select" required><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}" data-cost="{{ $product->purchase_cost ?: $product->wholesale_price }}">{{ $product->name }} ({{ $product->stock_quantity }} {{ $product->unit }})</option>@endforeach</select></td><td><input name="items[0][quantity]" type="number" min="1" value="1" class="form-control" required></td><td><input name="items[0][unit_cost]" type="number" min="0" step="0.01" class="form-control" required></td><td data-purchase-line-total>Rs 0.00</td><td><button type="button" class="btn btn-outline-danger" data-remove-purchase-row aria-label="Remove item"><i class="bi bi-x-lg"></i></button></td></tr></tbody></x-table>
<div class="d-flex justify-content-between align-items-center mt-3"><strong>Total <span data-purchase-total>Rs 0.00</span></strong><div class="d-flex gap-2"><a href="{{ route('business.purchases.index') }}" class="btn btn-outline-secondary">Cancel</a><button class="btn btn-tf-primary">Save purchase order</button></div></div></form>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('[data-purchase-form]');if(!form)return;const body=form.querySelector('[data-purchase-items]');const template=body.querySelector('[data-purchase-row]').outerHTML;const money=n=>'Rs '+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});const render=()=>{let total=0;body.querySelectorAll('[data-purchase-row]').forEach((row,i)=>{row.querySelectorAll('[name]').forEach(e=>e.name=e.name.replace(/items\[\d+\]/,'items['+i+']'));const select=row.querySelector('select'),cost=row.querySelector('[name$="[unit_cost]"]'),qty=row.querySelector('[name$="[quantity]"]');if(select.value&&!cost.value)cost.value=select.selectedOptions[0]?.dataset.cost||0;const line=(Number(qty.value)||0)*(Number(cost.value)||0);row.querySelector('[data-purchase-line-total]').textContent=money(line);total+=line;});form.querySelector('[data-purchase-total]').textContent=money(total);};form.querySelector('[data-add-purchase-row]').addEventListener('click',()=>{body.insertAdjacentHTML('beforeend',template);const row=body.lastElementChild;row.querySelector('select').value='';row.querySelectorAll('input').forEach((input)=>input.value=input.name.includes('quantity')?'1':'');render();});body.addEventListener('click',e=>{const button=e.target.closest('[data-remove-purchase-row]');if(button&&body.children.length>1){button.closest('[data-purchase-row]').remove();render();}});body.addEventListener('input',render);body.addEventListener('change',render);render();});</script>@endpush
