@extends('layouts.dashboard')
@section('page-title', 'Purchase '.$purchase->purchase_number)
@section('page-subtitle', 'Supplier order, receiving, payment, and returns')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><a href="{{ route('business.purchases.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Purchases</a><span class="tf-badge {{ $purchase->status === 'Received' ? 'tf-badge-success' : 'tf-badge-warning' }}">{{ $purchase->status }}</span></div>
<div class="row g-4">
    <div class="col-lg-8">
        <div class="tf-card p-4 mb-4"><div class="d-flex justify-content-between border-bottom pb-3 mb-3"><div><h2 class="h5 mb-1">{{ $purchase->supplier?->supplier_name }}</h2><small class="tf-muted">Supplier invoice: {{ $purchase->supplier_invoice_number ?: 'Not supplied' }}</small></div><div class="text-end"><strong>{{ $purchase->purchase_number }}</strong><small class="d-block tf-muted"><x-date-time :value="$purchase->purchase_date" /></small></div></div><x-table><thead><tr><th>Product</th><th>Ordered</th><th>Received</th><th>Cost</th><th>Total</th></tr></thead><tbody>@foreach($purchase->items as $item)<tr><td>{{ $item->product_name_snapshot }}</td><td>{{ $item->quantity }}</td><td>{{ $item->received_quantity }}</td><td>Rs {{ number_format($item->unit_cost, 2) }}</td><td>Rs {{ number_format($item->line_total, 2) }}</td></tr>@endforeach</tbody></x-table><div class="text-end mt-3"><div>Subtotal Rs {{ number_format($purchase->subtotal, 2) }}</div><div>Discount Rs {{ number_format($purchase->discount_amount, 2) }}</div><div>Tax Rs {{ number_format($purchase->tax_amount, 2) }}</div><strong class="fs-5">Total Rs {{ number_format($purchase->grand_total, 2) }}</strong></div></div>
        <div class="tf-card p-4"><h2 class="h5">Supplier payments</h2><x-table><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>@forelse($purchase->payments as $payment)<tr><td>{{ $payment->payment_date?->format('d M, Y') }}</td><td>{{ $payment->method }}</td><td>{{ $payment->reference_number ?: '—' }}</td><td>Rs {{ number_format($payment->amount, 2) }}</td></tr>@empty<tr><td colspan="4" class="text-center tf-muted">No payments recorded.</td></tr>@endforelse</tbody></x-table></div>
    </div>
    <div class="col-lg-4">
        <div class="tf-card p-4 mb-4"><h2 class="h5">Goods receipt</h2><p class="tf-muted small">Receiving goods increases inventory and posts Inventory Dr / Accounts Payable Cr.</p>@if($purchase->status === 'Ordered')@companyCan('purchases.receive')<form method="POST" action="{{ route('business.purchases.receive', $purchase) }}">@csrf<button class="btn btn-tf-primary w-100"><i class="bi bi-box-seam me-1"></i>Receive all goods</button></form>@endcompanyCan @else <p class="mb-0 text-success"><i class="bi bi-check-circle me-1"></i>Goods received {{ optional($purchase->received_at)->format('d M Y h:i A') }}</p>@endif</div>
        <div class="tf-card p-4 mb-4"><h2 class="h5">Payment control</h2><p class="small tf-muted">Paid Rs {{ number_format($purchase->paid_amount, 2) }} · Balance Rs {{ number_format($purchase->balance, 2) }}</p>@if($purchase->status !== 'Ordered' && $purchase->balance > 0)@companyCan('purchases.pay')<form method="POST" action="{{ route('business.purchases.pay', $purchase) }}" class="row g-2">@csrf<div class="col-12"><input name="amount" type="number" min="0.01" max="{{ $purchase->balance }}" step="0.01" class="form-control" placeholder="Payment amount" required></div><div class="col-12"><select name="method" class="form-select"><option>Cash</option><option>Bank Transfer</option><option>JazzCash Manual</option><option>Easypaisa Manual</option><option>Cheque</option></select></div><div class="col-12"><input name="reference_number" class="form-control" placeholder="Reference optional"></div><div class="col-12"><input name="payment_date" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-12"><button class="btn btn-outline-primary w-100">Record supplier payment</button></div></form>@endcompanyCan @endif</div>
        @if($purchase->status !== 'Ordered')@companyCan('purchase_returns.process')<div class="tf-card p-4"><h2 class="h5">Purchase return</h2><p class="tf-muted small">Open the dedicated return workflow to reverse inventory and supplier balances safely.</p><a href="{{ route('business.purchase-returns.create', ['purchase_id' => $purchase->id]) }}" class="btn btn-outline-warning w-100"><i class="bi bi-arrow-return-left me-1"></i>Start Purchase Return</a></div>@endcompanyCan@endif
    </div>
</div>
@endsection
