@extends('layouts.dashboard')
@section('page-title', 'Business Reports')
@section('page-subtitle', 'Read-only business analytics and report approval')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-3 mb-4">@foreach([['Total Businesses',$totalBusinesses],['Active Businesses',$activeBusinesses],['Total Platform Sales','Rs '.number_format($platformSales)],['Monthly Transactions','Rs '.number_format($monthlyTransactions)],['Pending Reports',$pendingReports],['Flagged Businesses',$flaggedBusinesses],['High Credit Businesses',$highCreditBusinesses],['Inactive Businesses',$inactiveBusinesses]] as [$label,$value])<div class="col-md-6 col-xl-3"><div class="tf-card p-4"><small class="tf-muted">{{ $label }}</small><div class="h3 fw-bold">{{ $value }}</div></div></div>@endforeach</div>

<div class="tf-card p-3 mb-3">
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-0">Filter Reports</h2><small class="tf-muted">Current time: {{ now()->timezone(config('app.timezone'))->format('n/j/Y h:i A') }}</small></div><div class="d-flex flex-wrap gap-2"><a href="{{ route('admin.business-reports.history', request()->query()) }}" class="btn btn-outline-primary"><i class="bi bi-clock-history me-1"></i>Report History</a><a href="{{ route('admin.business-reports.export.excel', request()->query()) }}" class="btn btn-outline-success"><i class="bi bi-file-earmark-spreadsheet me-1"></i>Export Excel</a><a href="{{ route('admin.business-reports.export.pdf', request()->query()) }}" target="_blank" rel="noopener" class="btn btn-outline-danger"><i class="bi bi-filetype-pdf me-1"></i>View PDF</a><a href="{{ route('admin.business-reports.export.pdf', array_merge(request()->query(), ['download' => 1])) }}" class="btn btn-outline-secondary"><i class="bi bi-download me-1"></i>Download PDF</a></div></div>
    <form method="GET" action="{{ route('admin.business-reports') }}" class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">Business</label><select name="business_id" class="form-select"><option value="">All businesses</option>@foreach($businesses as $business)<option value="{{ $business->id }}" @selected(request('business_id')==$business->id)>{{ $business->business_name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Report Type</label><input name="report_type" class="form-control" value="{{ request('report_type') }}" placeholder="Type"></div><div class="col-md-2"><label class="form-label">Date From</label><input name="date_from" type="date" class="form-control" value="{{ request('date_from', now()->timezone(config('app.timezone'))->toDateString()) }}"></div><div class="col-md-2"><label class="form-label">Date To</label><input name="date_to" type="date" class="form-control" value="{{ request('date_to', now()->timezone(config('app.timezone'))->toDateString()) }}"></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All statuses</option>@foreach(['Pending Review','Verified','Rejected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-outline-primary w-100">Filter</button></div></form>
</div>

<div class="dashboard-cards mb-4">@foreach([['Sales','Rs '.number_format($platformSummary['sales'] ?? 0),'bi-bag-check','bg-blue','Filtered period'],['Purchases','Rs '.number_format($platformSummary['purchases'] ?? 0),'bi-cart-plus','bg-amber','Filtered period'],['Expenses','Rs '.number_format($platformSummary['expenses'] ?? 0),'bi-receipt','bg-amber','Filtered period'],['Receivables','Rs '.number_format($platformSummary['receivables'] ?? 0),'bi-wallet2','bg-navy','Outstanding'],['Payables','Rs '.number_format($platformSummary['payables'] ?? 0),'bi-credit-card','bg-navy','Outstanding']] as [$label,$value,$icon,$color,$note])<div>@include('components.card',compact('label','value','icon','color','note'))</div>@endforeach</div>

<div class="tf-card p-4 mb-4"><h2 class="h5">Company-wise Performance</h2><x-table><thead><tr><th>Business</th><th>Sales</th><th>Expenses</th><th>Estimated Profit</th></tr></thead><tbody>@forelse($companySummaries as $business)<tr><td>{{ $business->business_name }}</td><td>Rs {{ number_format($business->sales_total ?? 0) }}</td><td>Rs {{ number_format($business->expense_total ?? 0) }}</td><td>Rs {{ number_format(($business->sales_total ?? 0)-($business->expense_total ?? 0)) }}</td></tr>@empty<tr><td colspan="4" class="text-center tf-muted">No data for the selected filters.</td></tr>@endforelse</tbody></x-table><div class="mt-3">{{ $companySummaries->links() }}</div></div>

@endsection
