@extends('layouts.dashboard')
@section('page-title', 'Business Reports')
@section('page-subtitle', 'Read-only business analytics and report approval')
@section('content')
<div class="row g-3 mb-4">@foreach([['Total Businesses',$totalBusinesses],['Active Businesses',$activeBusinesses],['Total Platform Sales','Rs '.number_format($platformSales)],['Monthly Transactions','Rs '.number_format($monthlyTransactions)],['Pending Reports',$pendingReports],['Flagged Businesses',$flaggedBusinesses],['High Credit Businesses',$highCreditBusinesses],['Inactive Businesses',$inactiveBusinesses]] as [$label,$value])<div class="col-md-6 col-xl-3"><div class="tf-card p-4"><small class="tf-muted">{{ $label }}</small><div class="h3 fw-bold">{{ $value }}</div></div></div>@endforeach</div>
<form class="row g-2 mb-3"><div class="col-md-3"><select name="business_id" class="form-select"><option value="">All businesses</option>@foreach($businesses as $business)<option value="{{ $business->id }}" @selected(request('business_id')==$business->id)>{{ $business->business_name }}</option>@endforeach</select></div><div class="col-md-2"><input name="report_type" class="form-control" value="{{ request('report_type') }}" placeholder="Type"></div><div class="col-md-2"><input name="date_from" type="date" class="form-control" value="{{ request('date_from') }}"></div><div class="col-md-2"><input name="date_to" type="date" class="form-control" value="{{ request('date_to') }}"></div><div class="col-md-1"><input name="month" type="number" min="1" max="12" class="form-control" value="{{ request('month') }}" placeholder="Month"></div><div class="col-md-1"><input name="year" type="number" min="2000" max="2100" class="form-control" value="{{ request('year') }}" placeholder="Year"></div><div class="col-md-2"><select name="status" class="form-select"><option value="">All statuses</option><option @selected(request('status')==='Pending Review')>Pending Review</option><option @selected(request('status')==='Verified')>Verified</option><option @selected(request('status')==='Rejected')>Rejected</option></select></div><div class="col-md-1"><button class="btn btn-outline-primary w-100">Go</button></div></form>
<div class="dashboard-cards mb-4">@foreach([['Sales','Rs '.number_format($platformSummary['sales'] ?? 0),'bi-bag-check','bg-blue','Filtered period'],['Purchases','Rs '.number_format($platformSummary['purchases'] ?? 0),'bi-cart-plus','bg-amber','Filtered period'],['Expenses','Rs '.number_format($platformSummary['expenses'] ?? 0),'bi-receipt','bg-amber','Filtered period'],['Receivables','Rs '.number_format($platformSummary['receivables'] ?? 0),'bi-wallet2','bg-navy','Outstanding'],['Payables','Rs '.number_format($platformSummary['payables'] ?? 0),'bi-credit-card','bg-navy','Outstanding']] as [$label,$value,$icon,$color,$note])<div>@include('components.card',compact('label','value','icon','color','note'))</div>@endforeach</div>
<div class="tf-card p-4 mb-4"><h2 class="h5">Company-wise Performance</h2><x-table><thead><tr><th>Business</th><th>Sales</th><th>Expenses</th><th>Estimated Profit</th></tr></thead><tbody>@forelse($companySummaries as $business)<tr><td>{{ $business->business_name }}</td><td>Rs {{ number_format($business->sales_total ?? 0) }}</td><td>Rs {{ number_format($business->expense_total ?? 0) }}</td><td>Rs {{ number_format(($business->sales_total ?? 0)-($business->expense_total ?? 0)) }}</td></tr>@empty<tr><td colspan="4" class="text-center tf-muted">No data for the selected filters.</td></tr>@endforelse</tbody></x-table></div>
<x-table><thead><tr><th>Business</th><th>Report Type</th><th>Month</th><th>Year</th><th>Total Sales</th><th>Total Orders</th><th>Expenses</th><th>Profit</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($reports as $report)<tr><td>{{ $report->business?->business_name }}</td><td>{{ $report->report_type }}</td><td>{{ $report->month }}</td><td>{{ $report->year }}</td><td>Rs {{ number_format($report->total_sales) }}</td><td>{{ $report->total_orders }}</td><td>Rs {{ number_format($report->total_expense) }}</td><td>Rs {{ number_format($report->profit) }}</td><td>{{ $report->status }}</td><td class="d-flex gap-1"><a href="{{ route('admin.business-reports.show',$report->business) }}" class="btn btn-sm btn-outline-primary">View</a><form method="POST" action="{{ route('admin.business-reports.approve',$report) }}">@csrf<button class="btn btn-sm btn-outline-success">Approve</button></form><form method="POST" action="{{ route('admin.business-reports.reject',$report) }}">@csrf<button class="btn btn-sm btn-outline-danger">Reject</button></form><a href="{{ route('admin.business-reports.pdf',$report) }}" target="_blank" rel="noopener" class="btn btn-sm btn-outline-secondary">PDF</a></td></tr>@empty<tr><td colspan="10" class="text-center tf-muted py-4">No reports.</td></tr>@endforelse</tbody></x-table>
@endsection
