@extends('layouts.dashboard')
@section('page-title', 'Purchase Returns')
@section('page-subtitle', 'Review supplier returns and related inventory reversals')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h5 mb-0">Purchase Returns</h2><p class="tf-muted mb-0">Returns are posted from their original purchase to keep inventory and payables accurate.</p></div><div class="d-flex gap-2"><a href="{{ route('business.purchases.index') }}" class="btn btn-outline-secondary">All Purchases</a><a href="{{ route('business.purchase-returns.create') }}" class="btn btn-tf-primary"><i class="bi bi-plus-lg me-1"></i>New Return</a></div></div>
<form class="tf-card p-3 mb-3 row g-2 align-items-end"><div class="col-md-5"><label class="form-label">Search return or purchase number</label><input name="search" value="{{ request('search') }}" class="form-control" autocomplete="off" autofocus></div><div class="col-md-2"><label class="form-label">Date From</label><input type="date" name="date_from" value="{{ request('date_from', now(config('app.timezone'))->toDateString()) }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Date To</label><input type="date" name="date_to" value="{{ request('date_to', now(config('app.timezone'))->toDateString()) }}" class="form-control"></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-outline-primary">Filter</button><a href="{{ route('business.purchase-returns.index') }}" class="btn btn-outline-secondary">Clear</a></div></form>
<x-table><thead><tr><th>Return</th><th>Purchase order</th><th>Supplier</th><th>Reason</th><th>Total</th><th></th></tr></thead><tbody>@forelse($returns as $return)<tr><td><strong>{{ $return->return_number }}</strong><small class="d-block tf-muted"><x-date-time :value="$return->return_date" /></small></td><td>{{ $return->purchase?->purchase_number ?? '—' }}</td><td>{{ $return->supplier?->supplier_name ?? '—' }}</td><td>{{ $return->reason }}</td><td>Rs {{ number_format($return->total_amount, 2) }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('business.purchase-returns.show', $return) }}">View</a></td></tr>@empty<tr><td colspan="6" class="text-center tf-muted py-5">No purchase returns found.</td></tr>@endforelse</tbody></x-table>
<div class="mt-3">{{ $returns->links() }}</div>
@endsection
