@extends('layouts.dashboard')
@section('page-title', 'Categories')
@section('page-subtitle', 'Manage product categories for this business')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
    <form method="GET" class="d-flex flex-wrap gap-2 align-items-center"><input name="search" class="form-control" style="min-width:220px" value="{{ request('search') }}" placeholder="Search categories"><select name="status" class="form-select" style="min-width:150px"><option value="">All</option><option value="Active" @selected(request('status') === 'Active')>Active</option><option value="Inactive" @selected(request('status') === 'Inactive')>Inactive</option><option value="Archived" @selected(request('status') === 'Archived' || request('archived'))>Archived</option></select><button class="btn btn-outline-primary">Filter</button><a class="btn btn-outline-secondary" href="{{ route('business.categories.index') }}">Clear</a></form>
    @companyCan('categories.create')<a class="btn btn-tf-primary" href="{{ route('business.categories.create') }}"><i class="bi bi-plus-lg me-1"></i>Add Category</a>@endcompanyCan
</div>
<x-table class="tf-business-data-table" data-tf-datatable><thead><tr><th>Category</th><th>Status</th><th>Created At</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($categories as $category)
<tr><td><strong>{{ $category->name }}</strong>@if($category->description)<div class="small tf-muted text-truncate" style="max-width:360px">{{ $category->description }}</div>@endif</td><td>@if($category->trashed())<span class="tf-badge tf-badge-warning">Archived</span>@else @companyCan('categories.status')<x-inline-status-switch :status="$category->status" :action="route('business.categories.status', $category)" entity="category {{ $category->name }}" />@else<span class="tf-badge {{ $category->status === 'Active' ? 'tf-badge-success' : 'tf-badge-secondary' }}">{{ $category->status }}</span>@endcompanyCan @endif</td><td><x-date-time :value="$category->created_at" /></td><td class="text-end text-nowrap"><div class="dropdown"><button class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" data-bs-boundary="viewport">Actions</button><div class="dropdown-menu dropdown-menu-end shadow-sm"><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#categoryDetailsModal{{ $category->id }}"><i class="bi bi-eye me-2"></i>View</button>@if(!$category->trashed())@companyCan('categories.edit')<a class="dropdown-item" href="{{ route('business.categories.edit', $category) }}"><i class="bi bi-pencil me-2"></i>Edit</a>@endcompanyCan @companyCan('categories.archive')<form method="POST" action="{{ route('business.categories.archive', $category) }}">@csrf @method('PATCH')<button class="dropdown-item text-warning" type="submit">Archive</button></form>@endcompanyCan @companyCan('categories.delete')<form method="POST" action="{{ route('business.categories.destroy', $category) }}" onsubmit="return confirm('Delete this unused category permanently?')">@csrf @method('DELETE')<button class="dropdown-item text-danger" type="submit">Delete</button></form>@endcompanyCan @else @companyCan('categories.archive')<form method="POST" action="{{ route('business.categories.restore', $category->id) }}">@csrf @method('PATCH')<button class="dropdown-item text-success" type="submit">Restore</button></form>@endcompanyCan @companyCan('categories.delete')<form method="POST" action="{{ route('business.categories.destroy', $category->id) }}" onsubmit="return confirm('Delete this archived category permanently?')">@csrf @method('DELETE')<button class="dropdown-item text-danger" type="submit">Permanently Delete</button></form>@endcompanyCan @endif</div></div></td></tr>
@empty<tr data-tf-datatable-empty><td colspan="4" class="text-center text-muted py-4">No categories found. Create categories before adding products.</td></tr>@endforelse
</tbody></x-table>
@foreach($categories as $category)
    <x-record-details-modal :id="'categoryDetailsModal'.$category->id" :title="$category->name" :status="$category->trashed() ? 'Archived' : $category->status" :open-url="route('business.categories.show', $category->id)" open-label="Open category record">
        <div class="tf-record-details-grid"><div><span>Status</span><strong>{{ $category->trashed() ? 'Archived' : $category->status }}</strong></div><div><span>Created</span><strong><x-date-time :value="$category->created_at" /></strong></div><div class="tf-record-details-wide"><span>Description</span><strong>{{ $category->description ?: 'Not provided' }}</strong></div></div>
    </x-record-details-modal>
@endforeach
@endsection
@push('scripts')
@if(session('error'))<script>document.addEventListener('DOMContentLoaded', () => Swal.fire({icon:'warning',text:@json(session('error'))}));</script>@endif
@endpush
