@extends('layouts.dashboard')

@section('page-title', 'Stock Count '.$stockCount->reference)
@section('page-subtitle', 'Read-only physical stock count record')

@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-3"><a href="{{ route('business.inventory.stock-counts.index') }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Stock Counts</a><span class="tf-badge {{ $stockCount->status === 'Completed' ? 'tf-badge-success' : 'tf-badge-secondary' }}">{{ $stockCount->status }}</span></div>
<div class="tf-card p-3 mb-3"><div class="row g-3"><div class="col-md-3"><span class="tf-muted small d-block">Reference</span><strong>{{ $stockCount->reference }}</strong></div><div class="col-md-3"><span class="tf-muted small d-block">Count date</span><x-date-time :value="$stockCount->counted_at" /></div><div class="col-md-3"><span class="tf-muted small d-block">Created by</span>{{ $stockCount->creator?->name ?? 'System' }}</div><div class="col-md-3"><span class="tf-muted small d-block">{{ $stockCount->status === 'Completed' ? 'Completed by' : 'Cancelled by' }}</span>{{ $stockCount->status === 'Completed' ? ($stockCount->completedBy?->name ?? 'System') : ($stockCount->cancelledBy?->name ?? 'System') }}</div>@if($stockCount->notes)<div class="col-12"><span class="tf-muted small d-block">Notes</span>{{ $stockCount->notes }}</div>@endif</div></div>
<div class="tf-card p-0 overflow-hidden"><div class="p-3 border-bottom"><h2 class="h6 mb-0">Count lines</h2></div><div class="table-responsive"><table class="table align-middle mb-0 tf-stock-count-table"><thead><tr><th>Product</th><th>Category</th><th>Unit</th><th>Snapshot Qty</th><th>Physical Qty</th><th>Variance</th><th>Applied</th><th>Reason</th><th>Notes</th></tr></thead><tbody>@forelse($stockCount->items as $item)<tr><td><strong>{{ $item->product?->name ?? 'Deleted product' }}</strong></td><td>{{ $item->product?->category?->name ?? '—' }}</td><td>{{ $item->product?->unit ?? '—' }}</td><td>{{ rtrim(rtrim(number_format($item->system_quantity, 3, '.', ''), '0'), '.') }}</td><td>{{ $item->physical_quantity === null ? '—' : rtrim(rtrim(number_format($item->physical_quantity, 3, '.', ''), '0'), '.') }}</td><td class="{{ (float)$item->variance < 0 ? 'text-danger' : ((float)$item->variance > 0 ? 'text-primary' : '') }}">{{ $item->variance === null ? '—' : rtrim(rtrim(number_format($item->variance, 3, '.', ''), '0'), '.') }}</td><td class="{{ (float)$item->applied_variance < 0 ? 'text-danger' : ((float)$item->applied_variance > 0 ? 'text-primary' : '') }}">{{ $item->applied_variance === null ? '—' : rtrim(rtrim(number_format($item->applied_variance, 3, '.', ''), '0'), '.') }}</td><td>{{ $item->reason ?? '—' }}</td><td>{{ $item->notes ?? '—' }}</td></tr>@empty<tr><td colspan="9" class="text-center tf-muted py-4">No products were added.</td></tr>@endforelse</tbody></table></div></div>
@endsection
