@extends('layouts.dashboard')
@section('page-title', 'Bulk Pricing')
@section('page-subtitle', 'Review and update product selling prices safely')
@section('content')
@php($priceFor = fn ($product) => $product->hasAcceptedPurchase() ? $product->currentPurchasePrice() : null)
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Pricing was not saved.</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-3"><div><h2 class="h5 mb-1">Product pricing</h2><p class="tf-muted mb-0">Purchase prices are receipt-controlled; only selling prices can be changed here.</p></div><a href="{{ route('business.products.index') }}" class="btn btn-outline-secondary">Back to Products</a></div>

<form method="GET" class="tf-card p-3 mb-3"><div class="row g-2 align-items-end"><div class="col-lg-3"><label class="form-label">Search product</label><input class="form-control" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Product name"></div><div class="col-lg-2"><label class="form-label">Category</label><select class="form-select" name="category_id"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id'] ?? null) == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-lg-2"><label class="form-label">Unit</label><select class="form-select" name="unit_id"><option value="">All units</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected(($filters['unit_id'] ?? null) == $unit->id)>{{ $unit->unit_name }}</option>@endforeach</select></div><div class="col-lg-2"><label class="form-label">Pricing status</label><select class="form-select" name="pricing_status"><option value="">All</option><option value="valid" @selected(($filters['pricing_status'] ?? null) === 'valid')>Valid Pricing</option><option value="needs" @selected(($filters['pricing_status'] ?? null) === 'needs')>Needs Pricing</option><option value="attention" @selected(($filters['pricing_status'] ?? null) === 'attention')>Pricing Attention</option></select></div><div class="col-lg-1"><label class="form-label">Rows</label><select class="form-select" name="per_page">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected(($filters['per_page'] ?? 10) == $size)>{{ $size }}</option>@endforeach</select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-outline-primary flex-grow-1">Filter</button><a class="btn btn-outline-secondary" href="{{ route('business.products.bulk-pricing') }}">Clear</a></div></div></form>

<form id="bulkPricingForm" method="POST" action="{{ route('business.products.bulk-pricing.update', request()->query()) }}" data-bulk-pricing-form>
@csrf @method('PATCH')
<div class="tf-card p-3 mb-3"><div class="d-flex flex-wrap align-items-end gap-2"><div><label class="form-label">Pricing mode</label><select class="form-select" data-pricing-mode><option value="selected">Selected Products</option><option value="category">Category-Wise</option></select></div><div><label class="form-label">Target</label><select class="form-select" data-pricing-target><option value="retail">Retail</option><option value="wholesale">Wholesale</option><option value="both" selected>Both</option></select></div><div><label class="form-label">Type</label><select class="form-select" data-pricing-type><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></div><div data-selected-markup-controls class="d-flex flex-wrap align-items-end gap-2"><div data-markup-field="retail"><label class="form-label" data-markup-label="retail">Retail Markup %</label><input class="form-control" type="number" min="0" max="1000" step="0.01" data-pricing-markup="retail" placeholder="0"></div><div data-markup-field="wholesale"><label class="form-label" data-markup-label="wholesale">Wholesale Markup %</label><input class="form-control" type="number" min="0" max="1000" step="0.01" data-pricing-markup="wholesale" placeholder="0"></div></div><button type="button" class="btn btn-outline-primary" data-apply-markup>Apply Markup</button></div><div class="mt-3 d-none" data-category-pricing><div class="small fw-semibold text-uppercase mb-2">Category pricing</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Category</th><th>Selected products</th><th data-category-heading="retail">Retail Markup %</th><th data-category-heading="wholesale">Wholesale Markup %</th></tr></thead><tbody data-category-pricing-rows></tbody></table></div></div><small class="tf-muted d-block mt-2" data-markup-message>Markup uses each selected product’s own purchase price. Products without a purchase price are skipped.</small></div>
<x-table class="tf-business-data-table tf-bulk-pricing-table"><thead><tr><th><input type="checkbox" aria-label="Select all visible products" data-pricing-select-all></th><th>Product</th><th>Category</th><th>Unit</th><th>Purchase</th><th>Current retail</th><th>Current wholesale</th><th>New retail</th><th>New wholesale</th><th>Retail margin</th><th>Wholesale margin</th><th>Status</th></tr></thead><tbody>
@forelse($products as $product)
@php($purchase = $priceFor($product)) @php($attention = $product->hasPricingAttention($purchase ?? 0)) @php($needs = $product->retail_price <= 0 || $product->wholesale_price <= 0)
<tr data-pricing-row data-purchase="{{ $purchase ?? '' }}" data-product="{{ $product->name }}" data-old-retail="{{ $product->retail_price }}" data-old-wholesale="{{ $product->wholesale_price }}"><td><input type="checkbox" data-pricing-select aria-label="Select {{ $product->name }}"><input type="hidden" name="rows[{{ $product->id }}][id]" value="{{ $product->id }}"></td><td><strong>{{ $product->name }}</strong></td><td>{{ $product->category?->name ?? '-' }}</td><td>{{ $product->unitRecord?->short_code ?? $product->unit ?? '-' }}</td><td>{{ $purchase === null ? '—' : 'Rs '.number_format($purchase, 2) }}</td><td>Rs {{ number_format($product->retail_price, 2) }}</td><td>Rs {{ number_format($product->wholesale_price, 2) }}</td><td><input class="form-control form-control-sm" data-pricing-input="retail" name="rows[{{ $product->id }}][retail_price]" value="{{ old('rows.'.$product->id.'.retail_price', $product->retail_price) }}" type="number" min="0" step="0.01"><small class="text-danger d-none" data-price-error="retail"></small></td><td><input class="form-control form-control-sm" data-pricing-input="wholesale" name="rows[{{ $product->id }}][wholesale_price]" value="{{ old('rows.'.$product->id.'.wholesale_price', $product->wholesale_price) }}" type="number" min="0" step="0.01"><small class="text-danger d-none" data-price-error="wholesale"></small></td><td data-margin="retail">—</td><td data-margin="wholesale">—</td><td data-pricing-status>@if($needs)<span class="tf-badge tf-badge-warning">Needs Pricing</span>@elseif($attention)<span class="tf-badge tf-badge-danger">Pricing Attention</span>@else<span class="tf-badge tf-badge-success">Valid Pricing</span>@endif</td></tr>
@empty<tr><td colspan="12" class="text-center tf-muted py-5">No products match these filters.</td></tr>@endforelse
</tbody></x-table>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mt-3"><div><x-table-result-summary :paginator="$products" />{{ $products->links('pagination::bootstrap-5') }}</div><button class="btn btn-tf-primary" type="submit" data-save-pricing><i class="bi bi-check2-circle me-1"></i>Save Changes</button></div>
</form>

<div class="modal fade tf-record-details-modal" data-tf-record-details-modal id="bulkPricingPreviewModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5 mb-0">Review pricing changes</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="tf-muted">Only changed products will be updated.</p><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Product</th><th>Purchase</th><th>Retail</th><th>Wholesale</th></tr></thead><tbody data-pricing-preview></tbody></table></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-tf-primary" type="button" data-apply-pricing>Apply Changes</button></div></div></div></div>
@endsection
@push('scripts')<script src="{{ asset('js/bulk-pricing.js') }}?v={{ filemtime(public_path('js/bulk-pricing.js')) }}"></script>@endpush
