@extends('layouts.dashboard')
@section('page-title', 'Platform Payments')
@section('page-subtitle', 'Payments received by TradeFlow from businesses')
@section('content')
<div class="tf-card p-4 mb-4">
    <h2 class="h5 mb-3">Record Business Payment</h2>
    <form method="POST" action="{{ route('admin.payments.store') }}" class="row g-3" data-tf-tab-order>@csrf
        <div class="col-md-4"><label class="form-label">Business</label><select name="business_id" class="form-select js-select2" required><option value="">Select business</option>@foreach($businesses as $business)<option value="{{ $business->id }}">{{ $business->business_name }}{{ $business->subscription?->plan ? ' — '.$business->subscription->plan->name : '' }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label">Amount</label><input name="amount" type="number" min="1" step="1" inputmode="numeric" class="form-control js-whole-number" required></div>
        <div class="col-md-2"><label class="form-label">Method</label><select name="method" class="form-select" required>@foreach(['Cash','Bank Transfer','JazzCash','Easypaisa','Cheque','Other'] as $method)<option>{{ $method }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select" required>@foreach(['Received','Pending','Rejected','Refunded'] as $status)<option>{{ $status }}</option>@endforeach</select></div>
        <div class="col-md-2"><label class="form-label">Paid At</label><input name="paid_at" type="datetime-local" value="{{ now()->format('Y-m-d\\TH:i') }}" class="form-control" required></div>
        <div class="col-md-4"><label class="form-label">Reference <span class="tf-muted">Optional</span></label><input name="reference_number" class="form-control" maxlength="120"></div>
        <div class="col-md-6"><label class="form-label">Notes <span class="tf-muted">Optional</span></label><input name="notes" class="form-control" maxlength="2000"></div>
        <div class="col-md-2 d-flex align-items-end"><button class="btn btn-tf-primary w-100">Record Payment</button></div>
    </form>
</div>
<div class="tf-card p-4 mb-4"><form method="GET" class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Business</label><select name="business_id" class="form-select js-select2"><option value="">All businesses</option>@foreach($businesses as $business)<option value="{{ $business->id }}" @selected(($filters['business_id'] ?? null) == $business->id)>{{ $business->business_name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All statuses</option>@foreach(['Received','Pending','Rejected','Refunded'] as $status)<option @selected(($filters['status'] ?? null) === $status)>{{ $status }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">From</label><input name="date_from" type="date" value="{{ $filters['date_from'] ?? '' }}" class="form-control"></div><div class="col-md-2"><label class="form-label">To</label><input name="date_to" type="date" value="{{ $filters['date_to'] ?? '' }}" class="form-control"></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-outline-primary flex-fill">Filter</button><a href="{{ route('admin.payments', ['clear' => 1]) }}" class="btn btn-outline-secondary">Clear</a></div></form></div>
<x-table><thead><tr><th>Business</th><th>Owner</th><th>Plan</th><th>Method</th><th>Reference</th><th>Amount</th><th>Status</th><th>Paid At</th><th>Recorded By</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->business?->business_name }}</td><td>{{ $payment->business?->owner?->name ?: '—' }}</td><td>{{ $payment->subscription?->plan?->name ?: '—' }}</td><td>{{ $payment->method }}</td><td>{{ $payment->reference_number ?: '—' }}</td><td>Rs {{ number_format($payment->amount, 2) }}</td><td><span class="tf-badge {{ $payment->status === 'Received' ? 'tf-badge-success' : ($payment->status === 'Pending' ? 'tf-badge-warning' : 'tf-badge-danger') }}">{{ $payment->status }}</span></td><td><x-date-time :value="$payment->paid_at" /></td><td>{{ $payment->recordedBy?->name ?: 'System' }}</td></tr>@empty<tr><td colspan="9" class="text-center tf-muted py-4">No platform payments have been recorded.</td></tr>@endforelse</tbody></x-table>
{{ $payments->links() }}
@endsection
